<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/annotations.proto

namespace Google\Genomics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * An annotation set is a logical grouping of annotations that share consistent
 * type information and provenance. Examples of annotation sets include 'all
 * genes from refseq', and 'all variant annotations from ClinVar'.
 * </pre>
 *
 * Protobuf type <code>google.genomics.v1.AnnotationSet</code>
 */
class AnnotationSet extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The server-generated annotation set ID, unique across all annotation sets.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * <pre>
     * The dataset to which this annotation set belongs.
     * </pre>
     *
     * <code>string dataset_id = 2;</code>
     */
    private $dataset_id = '';
    /**
     * <pre>
     * The ID of the reference set that defines the coordinate space for this
     * set's annotations.
     * </pre>
     *
     * <code>string reference_set_id = 3;</code>
     */
    private $reference_set_id = '';
    /**
     * <pre>
     * The display name for this annotation set.
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    private $name = '';
    /**
     * <pre>
     * The source URI describing the file from which this annotation set was
     * generated, if any.
     * </pre>
     *
     * <code>string source_uri = 5;</code>
     */
    private $source_uri = '';
    /**
     * <pre>
     * The type of annotations contained within this set.
     * </pre>
     *
     * <code>.google.genomics.v1.AnnotationType type = 6;</code>
     */
    private $type = 0;
    /**
     * <pre>
     * A map of additional read alignment information. This must be of the form
     * map&lt;string, string[]&gt; (string key mapping to a list of string values).
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.ListValue&gt; info = 17;</code>
     */
    private $info;

    public function __construct() {
        \GPBMetadata\Google\Genomics\V1\Annotations::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The server-generated annotation set ID, unique across all annotation sets.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <pre>
     * The server-generated annotation set ID, unique across all annotation sets.
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <pre>
     * The dataset to which this annotation set belongs.
     * </pre>
     *
     * <code>string dataset_id = 2;</code>
     */
    public function getDatasetId()
    {
        return $this->dataset_id;
    }

    /**
     * <pre>
     * The dataset to which this annotation set belongs.
     * </pre>
     *
     * <code>string dataset_id = 2;</code>
     */
    public function setDatasetId($var)
    {
        GPBUtil::checkString($var, True);
        $this->dataset_id = $var;
    }

    /**
     * <pre>
     * The ID of the reference set that defines the coordinate space for this
     * set's annotations.
     * </pre>
     *
     * <code>string reference_set_id = 3;</code>
     */
    public function getReferenceSetId()
    {
        return $this->reference_set_id;
    }

    /**
     * <pre>
     * The ID of the reference set that defines the coordinate space for this
     * set's annotations.
     * </pre>
     *
     * <code>string reference_set_id = 3;</code>
     */
    public function setReferenceSetId($var)
    {
        GPBUtil::checkString($var, True);
        $this->reference_set_id = $var;
    }

    /**
     * <pre>
     * The display name for this annotation set.
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * The display name for this annotation set.
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * The source URI describing the file from which this annotation set was
     * generated, if any.
     * </pre>
     *
     * <code>string source_uri = 5;</code>
     */
    public function getSourceUri()
    {
        return $this->source_uri;
    }

    /**
     * <pre>
     * The source URI describing the file from which this annotation set was
     * generated, if any.
     * </pre>
     *
     * <code>string source_uri = 5;</code>
     */
    public function setSourceUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_uri = $var;
    }

    /**
     * <pre>
     * The type of annotations contained within this set.
     * </pre>
     *
     * <code>.google.genomics.v1.AnnotationType type = 6;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <pre>
     * The type of annotations contained within this set.
     * </pre>
     *
     * <code>.google.genomics.v1.AnnotationType type = 6;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Google\Genomics\V1\AnnotationType::class);
        $this->type = $var;
    }

    /**
     * <pre>
     * A map of additional read alignment information. This must be of the form
     * map&lt;string, string[]&gt; (string key mapping to a list of string values).
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.ListValue&gt; info = 17;</code>
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * <pre>
     * A map of additional read alignment information. This must be of the form
     * map&lt;string, string[]&gt; (string key mapping to a list of string values).
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.ListValue&gt; info = 17;</code>
     */
    public function setInfo(&$var)
    {
        $this->info = $var;
    }

}

