<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/annotations.proto

namespace Google\Genomics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>google.genomics.v1.BatchCreateAnnotationsResponse.Entry</code>
 */
class BatchCreateAnnotationsResponse_Entry extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The creation status.
     * </pre>
     *
     * <code>.google.rpc.Status status = 1;</code>
     */
    private $status = null;
    /**
     * <pre>
     * The created annotation, if creation was successful.
     * </pre>
     *
     * <code>.google.genomics.v1.Annotation annotation = 2;</code>
     */
    private $annotation = null;

    public function __construct() {
        \GPBMetadata\Google\Genomics\V1\Annotations::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The creation status.
     * </pre>
     *
     * <code>.google.rpc.Status status = 1;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     * The creation status.
     * </pre>
     *
     * <code>.google.rpc.Status status = 1;</code>
     */
    public function setStatus(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Rpc\Status::class);
        $this->status = $var;
    }

    /**
     * <pre>
     * The created annotation, if creation was successful.
     * </pre>
     *
     * <code>.google.genomics.v1.Annotation annotation = 2;</code>
     */
    public function getAnnotation()
    {
        return $this->annotation;
    }

    /**
     * <pre>
     * The created annotation, if creation was successful.
     * </pre>
     *
     * <code>.google.genomics.v1.Annotation annotation = 2;</code>
     */
    public function setAnnotation(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Genomics\V1\Annotation::class);
        $this->annotation = $var;
    }

}

