<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/reads.proto

namespace Google\Genomics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * A bucket over which read coverage has been precomputed. A bucket corresponds
 * to a specific range of the reference sequence.
 * </pre>
 *
 * Protobuf type <code>google.genomics.v1.CoverageBucket</code>
 */
class CoverageBucket extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The genomic coordinate range spanned by this bucket.
     * </pre>
     *
     * <code>.google.genomics.v1.Range range = 1;</code>
     */
    private $range = null;
    /**
     * <pre>
     * The average number of reads which are aligned to each individual
     * reference base in this bucket.
     * </pre>
     *
     * <code>float mean_coverage = 2;</code>
     */
    private $mean_coverage = 0.0;

    public function __construct() {
        \GPBMetadata\Google\Genomics\V1\Reads::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The genomic coordinate range spanned by this bucket.
     * </pre>
     *
     * <code>.google.genomics.v1.Range range = 1;</code>
     */
    public function getRange()
    {
        return $this->range;
    }

    /**
     * <pre>
     * The genomic coordinate range spanned by this bucket.
     * </pre>
     *
     * <code>.google.genomics.v1.Range range = 1;</code>
     */
    public function setRange(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Genomics\V1\Range::class);
        $this->range = $var;
    }

    /**
     * <pre>
     * The average number of reads which are aligned to each individual
     * reference base in this bucket.
     * </pre>
     *
     * <code>float mean_coverage = 2;</code>
     */
    public function getMeanCoverage()
    {
        return $this->mean_coverage;
    }

    /**
     * <pre>
     * The average number of reads which are aligned to each individual
     * reference base in this bucket.
     * </pre>
     *
     * <code>float mean_coverage = 2;</code>
     */
    public function setMeanCoverage($var)
    {
        GPBUtil::checkFloat($var);
        $this->mean_coverage = $var;
    }

}

