<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/variants.proto

namespace Google\Genomics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>google.genomics.v1.CreateCallSetRequest</code>
 */
class CreateCallSetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The call set to be created.
     * </pre>
     *
     * <code>.google.genomics.v1.CallSet call_set = 1;</code>
     */
    private $call_set = null;

    public function __construct() {
        \GPBMetadata\Google\Genomics\V1\Variants::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The call set to be created.
     * </pre>
     *
     * <code>.google.genomics.v1.CallSet call_set = 1;</code>
     */
    public function getCallSet()
    {
        return $this->call_set;
    }

    /**
     * <pre>
     * The call set to be created.
     * </pre>
     *
     * <code>.google.genomics.v1.CallSet call_set = 1;</code>
     */
    public function setCallSet(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Genomics\V1\CallSet::class);
        $this->call_set = $var;
    }

}

