<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/annotations.proto

namespace Google\Genomics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>google.genomics.v1.CreateAnnotationRequest</code>
 */
class CreateAnnotationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The annotation to be created.
     * </pre>
     *
     * <code>.google.genomics.v1.Annotation annotation = 1;</code>
     */
    private $annotation = null;

    public function __construct() {
        \GPBMetadata\Google\Genomics\V1\Annotations::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The annotation to be created.
     * </pre>
     *
     * <code>.google.genomics.v1.Annotation annotation = 1;</code>
     */
    public function getAnnotation()
    {
        return $this->annotation;
    }

    /**
     * <pre>
     * The annotation to be created.
     * </pre>
     *
     * <code>.google.genomics.v1.Annotation annotation = 1;</code>
     */
    public function setAnnotation(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Genomics\V1\Annotation::class);
        $this->annotation = $var;
    }

}

