<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/variants.proto

namespace Google\Genomics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>google.genomics.v1.DeleteCallSetRequest</code>
 */
class DeleteCallSetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The ID of the call set to be deleted.
     * </pre>
     *
     * <code>string call_set_id = 1;</code>
     */
    private $call_set_id = '';

    public function __construct() {
        \GPBMetadata\Google\Genomics\V1\Variants::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The ID of the call set to be deleted.
     * </pre>
     *
     * <code>string call_set_id = 1;</code>
     */
    public function getCallSetId()
    {
        return $this->call_set_id;
    }

    /**
     * <pre>
     * The ID of the call set to be deleted.
     * </pre>
     *
     * <code>string call_set_id = 1;</code>
     */
    public function setCallSetId($var)
    {
        GPBUtil::checkString($var, True);
        $this->call_set_id = $var;
    }

}

