<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/references.proto

namespace Google\Genomics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>google.genomics.v1.GetReferenceSetRequest</code>
 */
class GetReferenceSetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The ID of the reference set.
     * </pre>
     *
     * <code>string reference_set_id = 1;</code>
     */
    private $reference_set_id = '';

    public function __construct() {
        \GPBMetadata\Google\Genomics\V1\References::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The ID of the reference set.
     * </pre>
     *
     * <code>string reference_set_id = 1;</code>
     */
    public function getReferenceSetId()
    {
        return $this->reference_set_id;
    }

    /**
     * <pre>
     * The ID of the reference set.
     * </pre>
     *
     * <code>string reference_set_id = 1;</code>
     */
    public function setReferenceSetId($var)
    {
        GPBUtil::checkString($var, True);
        $this->reference_set_id = $var;
    }

}

