<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/variants.proto

namespace Google\Genomics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * The variant data import request.
 * </pre>
 *
 * Protobuf type <code>google.genomics.v1.ImportVariantsRequest</code>
 */
class ImportVariantsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Required. The variant set to which variant data should be imported.
     * </pre>
     *
     * <code>string variant_set_id = 1;</code>
     */
    private $variant_set_id = '';
    /**
     * <pre>
     * A list of URIs referencing variant files in Google Cloud Storage. URIs can
     * include wildcards [as described
     * here](https://cloud.google.com/storage/docs/gsutil/addlhelp/WildcardNames).
     * Note that recursive wildcards ('**') are not supported.
     * </pre>
     *
     * <code>repeated string source_uris = 2;</code>
     */
    private $source_uris;
    /**
     * <pre>
     * The format of the variant data being imported. If unspecified, defaults to
     * to `VCF`.
     * </pre>
     *
     * <code>.google.genomics.v1.ImportVariantsRequest.Format format = 3;</code>
     */
    private $format = 0;
    /**
     * <pre>
     * Convert reference names to the canonical representation.
     * hg19 haploytypes (those reference names containing "_hap")
     * are not modified in any way.
     * All other reference names are modified according to the following rules:
     * The reference name is capitalized.
     * The "chr" prefix is dropped for all autosomes and sex chromsomes.
     * For example "chr17" becomes "17" and "chrX" becomes "X".
     * All mitochondrial chromosomes ("chrM", "chrMT", etc) become "MT".
     * </pre>
     *
     * <code>bool normalize_reference_names = 5;</code>
     */
    private $normalize_reference_names = false;
    /**
     * <pre>
     * A mapping between info field keys and the InfoMergeOperations to
     * be performed on them. This is plumbed down to the MergeVariantRequests
     * generated by the resulting import job.
     * </pre>
     *
     * <code>map&lt;string, .google.genomics.v1.InfoMergeOperation&gt; info_merge_config = 6;</code>
     */
    private $info_merge_config;

    public function __construct() {
        \GPBMetadata\Google\Genomics\V1\Variants::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Required. The variant set to which variant data should be imported.
     * </pre>
     *
     * <code>string variant_set_id = 1;</code>
     */
    public function getVariantSetId()
    {
        return $this->variant_set_id;
    }

    /**
     * <pre>
     * Required. The variant set to which variant data should be imported.
     * </pre>
     *
     * <code>string variant_set_id = 1;</code>
     */
    public function setVariantSetId($var)
    {
        GPBUtil::checkString($var, True);
        $this->variant_set_id = $var;
    }

    /**
     * <pre>
     * A list of URIs referencing variant files in Google Cloud Storage. URIs can
     * include wildcards [as described
     * here](https://cloud.google.com/storage/docs/gsutil/addlhelp/WildcardNames).
     * Note that recursive wildcards ('**') are not supported.
     * </pre>
     *
     * <code>repeated string source_uris = 2;</code>
     */
    public function getSourceUris()
    {
        return $this->source_uris;
    }

    /**
     * <pre>
     * A list of URIs referencing variant files in Google Cloud Storage. URIs can
     * include wildcards [as described
     * here](https://cloud.google.com/storage/docs/gsutil/addlhelp/WildcardNames).
     * Note that recursive wildcards ('**') are not supported.
     * </pre>
     *
     * <code>repeated string source_uris = 2;</code>
     */
    public function setSourceUris(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->source_uris = $var;
    }

    /**
     * <pre>
     * The format of the variant data being imported. If unspecified, defaults to
     * to `VCF`.
     * </pre>
     *
     * <code>.google.genomics.v1.ImportVariantsRequest.Format format = 3;</code>
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * <pre>
     * The format of the variant data being imported. If unspecified, defaults to
     * to `VCF`.
     * </pre>
     *
     * <code>.google.genomics.v1.ImportVariantsRequest.Format format = 3;</code>
     */
    public function setFormat($var)
    {
        GPBUtil::checkEnum($var, \Google\Genomics\V1\ImportVariantsRequest_Format::class);
        $this->format = $var;
    }

    /**
     * <pre>
     * Convert reference names to the canonical representation.
     * hg19 haploytypes (those reference names containing "_hap")
     * are not modified in any way.
     * All other reference names are modified according to the following rules:
     * The reference name is capitalized.
     * The "chr" prefix is dropped for all autosomes and sex chromsomes.
     * For example "chr17" becomes "17" and "chrX" becomes "X".
     * All mitochondrial chromosomes ("chrM", "chrMT", etc) become "MT".
     * </pre>
     *
     * <code>bool normalize_reference_names = 5;</code>
     */
    public function getNormalizeReferenceNames()
    {
        return $this->normalize_reference_names;
    }

    /**
     * <pre>
     * Convert reference names to the canonical representation.
     * hg19 haploytypes (those reference names containing "_hap")
     * are not modified in any way.
     * All other reference names are modified according to the following rules:
     * The reference name is capitalized.
     * The "chr" prefix is dropped for all autosomes and sex chromsomes.
     * For example "chr17" becomes "17" and "chrX" becomes "X".
     * All mitochondrial chromosomes ("chrM", "chrMT", etc) become "MT".
     * </pre>
     *
     * <code>bool normalize_reference_names = 5;</code>
     */
    public function setNormalizeReferenceNames($var)
    {
        GPBUtil::checkBool($var);
        $this->normalize_reference_names = $var;
    }

    /**
     * <pre>
     * A mapping between info field keys and the InfoMergeOperations to
     * be performed on them. This is plumbed down to the MergeVariantRequests
     * generated by the resulting import job.
     * </pre>
     *
     * <code>map&lt;string, .google.genomics.v1.InfoMergeOperation&gt; info_merge_config = 6;</code>
     */
    public function getInfoMergeConfig()
    {
        return $this->info_merge_config;
    }

    /**
     * <pre>
     * A mapping between info field keys and the InfoMergeOperations to
     * be performed on them. This is plumbed down to the MergeVariantRequests
     * generated by the resulting import job.
     * </pre>
     *
     * <code>map&lt;string, .google.genomics.v1.InfoMergeOperation&gt; info_merge_config = 6;</code>
     */
    public function setInfoMergeConfig(&$var)
    {
        $this->info_merge_config = $var;
    }

}

