<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/variants.proto

namespace Google\Genomics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>google.genomics.v1.UpdateCallSetRequest</code>
 */
class UpdateCallSetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The ID of the call set to be updated.
     * </pre>
     *
     * <code>string call_set_id = 1;</code>
     */
    private $call_set_id = '';
    /**
     * <pre>
     * The new call set data.
     * </pre>
     *
     * <code>.google.genomics.v1.CallSet call_set = 2;</code>
     */
    private $call_set = null;
    /**
     * <pre>
     * An optional mask specifying which fields to update. At this time, the only
     * mutable field is [name][google.genomics.v1.CallSet.name]. The only
     * acceptable value is "name". If unspecified, all mutable fields will be
     * updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    private $update_mask = null;

    public function __construct() {
        \GPBMetadata\Google\Genomics\V1\Variants::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The ID of the call set to be updated.
     * </pre>
     *
     * <code>string call_set_id = 1;</code>
     */
    public function getCallSetId()
    {
        return $this->call_set_id;
    }

    /**
     * <pre>
     * The ID of the call set to be updated.
     * </pre>
     *
     * <code>string call_set_id = 1;</code>
     */
    public function setCallSetId($var)
    {
        GPBUtil::checkString($var, True);
        $this->call_set_id = $var;
    }

    /**
     * <pre>
     * The new call set data.
     * </pre>
     *
     * <code>.google.genomics.v1.CallSet call_set = 2;</code>
     */
    public function getCallSet()
    {
        return $this->call_set;
    }

    /**
     * <pre>
     * The new call set data.
     * </pre>
     *
     * <code>.google.genomics.v1.CallSet call_set = 2;</code>
     */
    public function setCallSet(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Genomics\V1\CallSet::class);
        $this->call_set = $var;
    }

    /**
     * <pre>
     * An optional mask specifying which fields to update. At this time, the only
     * mutable field is [name][google.genomics.v1.CallSet.name]. The only
     * acceptable value is "name". If unspecified, all mutable fields will be
     * updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    /**
     * <pre>
     * An optional mask specifying which fields to update. At this time, the only
     * mutable field is [name][google.genomics.v1.CallSet.name]. The only
     * acceptable value is "name". If unspecified, all mutable fields will be
     * updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    public function setUpdateMask(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;
    }

}

