<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/variants.proto

namespace Google\Genomics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>google.genomics.v1.UpdateVariantRequest</code>
 */
class UpdateVariantRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The ID of the variant to be updated.
     * </pre>
     *
     * <code>string variant_id = 1;</code>
     */
    private $variant_id = '';
    /**
     * <pre>
     * The new variant data.
     * </pre>
     *
     * <code>.google.genomics.v1.Variant variant = 2;</code>
     */
    private $variant = null;
    /**
     * <pre>
     * An optional mask specifying which fields to update. At this time, mutable
     * fields are [names][google.genomics.v1.Variant.names] and
     * [info][google.genomics.v1.Variant.info]. Acceptable values are "names" and
     * "info". If unspecified, all mutable fields will be updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    private $update_mask = null;

    public function __construct() {
        \GPBMetadata\Google\Genomics\V1\Variants::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The ID of the variant to be updated.
     * </pre>
     *
     * <code>string variant_id = 1;</code>
     */
    public function getVariantId()
    {
        return $this->variant_id;
    }

    /**
     * <pre>
     * The ID of the variant to be updated.
     * </pre>
     *
     * <code>string variant_id = 1;</code>
     */
    public function setVariantId($var)
    {
        GPBUtil::checkString($var, True);
        $this->variant_id = $var;
    }

    /**
     * <pre>
     * The new variant data.
     * </pre>
     *
     * <code>.google.genomics.v1.Variant variant = 2;</code>
     */
    public function getVariant()
    {
        return $this->variant;
    }

    /**
     * <pre>
     * The new variant data.
     * </pre>
     *
     * <code>.google.genomics.v1.Variant variant = 2;</code>
     */
    public function setVariant(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Genomics\V1\Variant::class);
        $this->variant = $var;
    }

    /**
     * <pre>
     * An optional mask specifying which fields to update. At this time, mutable
     * fields are [names][google.genomics.v1.Variant.names] and
     * [info][google.genomics.v1.Variant.info]. Acceptable values are "names" and
     * "info". If unspecified, all mutable fields will be updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    /**
     * <pre>
     * An optional mask specifying which fields to update. At this time, mutable
     * fields are [names][google.genomics.v1.Variant.names] and
     * [info][google.genomics.v1.Variant.info]. Acceptable values are "names" and
     * "info". If unspecified, all mutable fields will be updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    public function setUpdateMask(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;
    }

}

