<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/annotations.proto

namespace Google\Genomics\V1;

/**
 * Protobuf enum <code>google.genomics.v1.VariantAnnotation.ClinicalSignificance</code>
 */
class VariantAnnotation_ClinicalSignificance
{
    /**
     * <code>CLINICAL_SIGNIFICANCE_UNSPECIFIED = 0;</code>
     */
    const CLINICAL_SIGNIFICANCE_UNSPECIFIED = 0;
    /**
     * <pre>
     * `OTHER` should be used when no other clinical significance
     * value will suffice.
     * </pre>
     *
     * <code>CLINICAL_SIGNIFICANCE_OTHER = 1;</code>
     */
    const CLINICAL_SIGNIFICANCE_OTHER = 1;
    /**
     * <code>UNCERTAIN = 2;</code>
     */
    const UNCERTAIN = 2;
    /**
     * <code>BENIGN = 3;</code>
     */
    const BENIGN = 3;
    /**
     * <code>LIKELY_BENIGN = 4;</code>
     */
    const LIKELY_BENIGN = 4;
    /**
     * <code>LIKELY_PATHOGENIC = 5;</code>
     */
    const LIKELY_PATHOGENIC = 5;
    /**
     * <code>PATHOGENIC = 6;</code>
     */
    const PATHOGENIC = 6;
    /**
     * <code>DRUG_RESPONSE = 7;</code>
     */
    const DRUG_RESPONSE = 7;
    /**
     * <code>HISTOCOMPATIBILITY = 8;</code>
     */
    const HISTOCOMPATIBILITY = 8;
    /**
     * <code>CONFERS_SENSITIVITY = 9;</code>
     */
    const CONFERS_SENSITIVITY = 9;
    /**
     * <code>RISK_FACTOR = 10;</code>
     */
    const RISK_FACTOR = 10;
    /**
     * <code>ASSOCIATION = 11;</code>
     */
    const ASSOCIATION = 11;
    /**
     * <code>PROTECTIVE = 12;</code>
     */
    const PROTECTIVE = 12;
    /**
     * <pre>
     * `MULTIPLE_REPORTED` should be used when multiple clinical
     * signficances are reported for a variant. The original clinical
     * significance values may be provided in the `info` field.
     * </pre>
     *
     * <code>MULTIPLE_REPORTED = 13;</code>
     */
    const MULTIPLE_REPORTED = 13;
}

