<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/annotations.proto

namespace Google\Genomics\V1;

/**
 * Protobuf enum <code>google.genomics.v1.VariantAnnotation.Effect</code>
 */
class VariantAnnotation_Effect
{
    /**
     * <code>EFFECT_UNSPECIFIED = 0;</code>
     */
    const EFFECT_UNSPECIFIED = 0;
    /**
     * <pre>
     * `EFFECT_OTHER` should be used when no other Effect
     * will suffice.
     * </pre>
     *
     * <code>EFFECT_OTHER = 1;</code>
     */
    const EFFECT_OTHER = 1;
    /**
     * <pre>
     * `FRAMESHIFT` indicates a mutation in which the insertion or
     * deletion of nucleotides resulted in a frameshift change.
     * </pre>
     *
     * <code>FRAMESHIFT = 2;</code>
     */
    const FRAMESHIFT = 2;
    /**
     * <pre>
     * `FRAME_PRESERVING_INDEL` indicates a mutation in which a
     * multiple of three nucleotides has been inserted or deleted, resulting
     * in no change to the reading frame of the coding sequence.
     * </pre>
     *
     * <code>FRAME_PRESERVING_INDEL = 3;</code>
     */
    const FRAME_PRESERVING_INDEL = 3;
    /**
     * <pre>
     * `SYNONYMOUS_SNP` indicates a single nucleotide polymorphism
     * mutation that results in no amino acid change.
     * </pre>
     *
     * <code>SYNONYMOUS_SNP = 4;</code>
     */
    const SYNONYMOUS_SNP = 4;
    /**
     * <pre>
     * `NONSYNONYMOUS_SNP` indicates a single nucleotide
     * polymorphism mutation that results in an amino acid change.
     * </pre>
     *
     * <code>NONSYNONYMOUS_SNP = 5;</code>
     */
    const NONSYNONYMOUS_SNP = 5;
    /**
     * <pre>
     * `STOP_GAIN` indicates a mutation that leads to the creation
     * of a stop codon at the variant site. Frameshift mutations creating
     * downstream stop codons do not count as `STOP_GAIN`.
     * </pre>
     *
     * <code>STOP_GAIN = 6;</code>
     */
    const STOP_GAIN = 6;
    /**
     * <pre>
     * `STOP_LOSS` indicates a mutation that eliminates a
     * stop codon at the variant site.
     * </pre>
     *
     * <code>STOP_LOSS = 7;</code>
     */
    const STOP_LOSS = 7;
    /**
     * <pre>
     * `SPLICE_SITE_DISRUPTION` indicates that this variant is
     * found in a splice site for the associated transcript, and alters the
     * normal splicing pattern.
     * </pre>
     *
     * <code>SPLICE_SITE_DISRUPTION = 8;</code>
     */
    const SPLICE_SITE_DISRUPTION = 8;
}

