<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/container/v1/cluster_service.proto

namespace Google\Container\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * AutoUpgradeOptions defines the set of options for the user to control how
 * the Auto Upgrades will proceed.
 * </pre>
 *
 * Protobuf type <code>google.container.v1.AutoUpgradeOptions</code>
 */
class AutoUpgradeOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * [Output only] This field is set when upgrades are about to commence
     * with the approximate start time for the upgrades, in
     * [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
     * </pre>
     *
     * <code>string auto_upgrade_start_time = 1;</code>
     */
    private $auto_upgrade_start_time = '';
    /**
     * <pre>
     * [Output only] This field is set when upgrades are about to commence
     * with the description of the upgrade.
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    private $description = '';

    public function __construct() {
        \GPBMetadata\Google\Container\V1\ClusterService::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * [Output only] This field is set when upgrades are about to commence
     * with the approximate start time for the upgrades, in
     * [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
     * </pre>
     *
     * <code>string auto_upgrade_start_time = 1;</code>
     */
    public function getAutoUpgradeStartTime()
    {
        return $this->auto_upgrade_start_time;
    }

    /**
     * <pre>
     * [Output only] This field is set when upgrades are about to commence
     * with the approximate start time for the upgrades, in
     * [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
     * </pre>
     *
     * <code>string auto_upgrade_start_time = 1;</code>
     */
    public function setAutoUpgradeStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->auto_upgrade_start_time = $var;
    }

    /**
     * <pre>
     * [Output only] This field is set when upgrades are about to commence
     * with the description of the upgrade.
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * <pre>
     * [Output only] This field is set when upgrades are about to commence
     * with the description of the upgrade.
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

}

