<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/container/v1/cluster_service.proto

namespace Google\Container\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Configuration for the legacy Attribute Based Access Control authorization
 * mode.
 * </pre>
 *
 * Protobuf type <code>google.container.v1.LegacyAbac</code>
 */
class LegacyAbac extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Whether the ABAC authorizer is enabled for this cluster. When enabled,
     * identities in the system, including service accounts, nodes, and
     * controllers, will have statically granted permissions beyond those
     * provided by the RBAC configuration or IAM.
     * </pre>
     *
     * <code>bool enabled = 1;</code>
     */
    private $enabled = false;

    public function __construct() {
        \GPBMetadata\Google\Container\V1\ClusterService::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Whether the ABAC authorizer is enabled for this cluster. When enabled,
     * identities in the system, including service accounts, nodes, and
     * controllers, will have statically granted permissions beyond those
     * provided by the RBAC configuration or IAM.
     * </pre>
     *
     * <code>bool enabled = 1;</code>
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * <pre>
     * Whether the ABAC authorizer is enabled for this cluster. When enabled,
     * identities in the system, including service accounts, nodes, and
     * controllers, will have statically granted permissions beyond those
     * provided by the RBAC configuration or IAM.
     * </pre>
     *
     * <code>bool enabled = 1;</code>
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;
    }

}

