<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/container/v1/cluster_service.proto

namespace Google\Container\V1;

/**
 * <pre>
 * The current status of the node pool instance.
 * </pre>
 *
 * Protobuf enum <code>google.container.v1.NodePool.Status</code>
 */
class NodePool_Status
{
    /**
     * <pre>
     * Not set.
     * </pre>
     *
     * <code>STATUS_UNSPECIFIED = 0;</code>
     */
    const STATUS_UNSPECIFIED = 0;
    /**
     * <pre>
     * The PROVISIONING state indicates the node pool is being created.
     * </pre>
     *
     * <code>PROVISIONING = 1;</code>
     */
    const PROVISIONING = 1;
    /**
     * <pre>
     * The RUNNING state indicates the node pool has been created
     * and is fully usable.
     * </pre>
     *
     * <code>RUNNING = 2;</code>
     */
    const RUNNING = 2;
    /**
     * <pre>
     * The RUNNING_WITH_ERROR state indicates the node pool has been created
     * and is partially usable. Some error state has occurred and some
     * functionality may be impaired. Customer may need to reissue a request
     * or trigger a new update.
     * </pre>
     *
     * <code>RUNNING_WITH_ERROR = 3;</code>
     */
    const RUNNING_WITH_ERROR = 3;
    /**
     * <pre>
     * The RECONCILING state indicates that some work is actively being done on
     * the node pool, such as upgrading node software. Details can
     * be found in the `statusMessage` field.
     * </pre>
     *
     * <code>RECONCILING = 4;</code>
     */
    const RECONCILING = 4;
    /**
     * <pre>
     * The STOPPING state indicates the node pool is being deleted.
     * </pre>
     *
     * <code>STOPPING = 5;</code>
     */
    const STOPPING = 5;
    /**
     * <pre>
     * The ERROR state indicates the node pool may be unusable. Details
     * can be found in the `statusMessage` field.
     * </pre>
     *
     * <code>ERROR = 6;</code>
     */
    const ERROR = 6;
}

