<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/container/v1/cluster_service.proto

namespace Google\Container\V1;

/**
 * <pre>
 * Operation type.
 * </pre>
 *
 * Protobuf enum <code>google.container.v1.Operation.Type</code>
 */
class Operation_Type
{
    /**
     * <pre>
     * Not set.
     * </pre>
     *
     * <code>TYPE_UNSPECIFIED = 0;</code>
     */
    const TYPE_UNSPECIFIED = 0;
    /**
     * <pre>
     * Cluster create.
     * </pre>
     *
     * <code>CREATE_CLUSTER = 1;</code>
     */
    const CREATE_CLUSTER = 1;
    /**
     * <pre>
     * Cluster delete.
     * </pre>
     *
     * <code>DELETE_CLUSTER = 2;</code>
     */
    const DELETE_CLUSTER = 2;
    /**
     * <pre>
     * A master upgrade.
     * </pre>
     *
     * <code>UPGRADE_MASTER = 3;</code>
     */
    const UPGRADE_MASTER = 3;
    /**
     * <pre>
     * A node upgrade.
     * </pre>
     *
     * <code>UPGRADE_NODES = 4;</code>
     */
    const UPGRADE_NODES = 4;
    /**
     * <pre>
     * Cluster repair.
     * </pre>
     *
     * <code>REPAIR_CLUSTER = 5;</code>
     */
    const REPAIR_CLUSTER = 5;
    /**
     * <pre>
     * Cluster update.
     * </pre>
     *
     * <code>UPDATE_CLUSTER = 6;</code>
     */
    const UPDATE_CLUSTER = 6;
    /**
     * <pre>
     * Node pool create.
     * </pre>
     *
     * <code>CREATE_NODE_POOL = 7;</code>
     */
    const CREATE_NODE_POOL = 7;
    /**
     * <pre>
     * Node pool delete.
     * </pre>
     *
     * <code>DELETE_NODE_POOL = 8;</code>
     */
    const DELETE_NODE_POOL = 8;
    /**
     * <pre>
     * Set node pool management.
     * </pre>
     *
     * <code>SET_NODE_POOL_MANAGEMENT = 9;</code>
     */
    const SET_NODE_POOL_MANAGEMENT = 9;
    /**
     * <pre>
     * Automatic node pool repair.
     * </pre>
     *
     * <code>AUTO_REPAIR_NODES = 10;</code>
     */
    const AUTO_REPAIR_NODES = 10;
    /**
     * <pre>
     * Automatic node upgrade.
     * </pre>
     *
     * <code>AUTO_UPGRADE_NODES = 11;</code>
     */
    const AUTO_UPGRADE_NODES = 11;
    /**
     * <pre>
     * Set labels.
     * </pre>
     *
     * <code>SET_LABELS = 12;</code>
     */
    const SET_LABELS = 12;
    /**
     * <pre>
     * Set/generate master auth materials
     * </pre>
     *
     * <code>SET_MASTER_AUTH = 13;</code>
     */
    const SET_MASTER_AUTH = 13;
}

