<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/storagetransfer/v1/transfer_types.proto

namespace Google\Storagetransfer\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * An entry describing an error that has occurred.
 * </pre>
 *
 * Protobuf type <code>google.storagetransfer.v1.ErrorLogEntry</code>
 */
class ErrorLogEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * A URL that refers to the target (a data source, a data sink,
     * or an object) with which the error is associated.
     * Required.
     * </pre>
     *
     * <code>string url = 1;</code>
     */
    private $url = '';
    /**
     * <pre>
     * A list of messages that carry the error details.
     * </pre>
     *
     * <code>repeated string error_details = 3;</code>
     */
    private $error_details;

    public function __construct() {
        \GPBMetadata\Google\Storagetransfer\V1\TransferTypes::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * A URL that refers to the target (a data source, a data sink,
     * or an object) with which the error is associated.
     * Required.
     * </pre>
     *
     * <code>string url = 1;</code>
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * <pre>
     * A URL that refers to the target (a data source, a data sink,
     * or an object) with which the error is associated.
     * Required.
     * </pre>
     *
     * <code>string url = 1;</code>
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;
    }

    /**
     * <pre>
     * A list of messages that carry the error details.
     * </pre>
     *
     * <code>repeated string error_details = 3;</code>
     */
    public function getErrorDetails()
    {
        return $this->error_details;
    }

    /**
     * <pre>
     * A list of messages that carry the error details.
     * </pre>
     *
     * <code>repeated string error_details = 3;</code>
     */
    public function setErrorDetails(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->error_details = $arr;
    }

}

