<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/storagetransfer/v1/transfer.proto

namespace Google\Storagetransfer\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response from ListTransferJobs.
 * </pre>
 *
 * Protobuf type <code>google.storagetransfer.v1.ListTransferJobsResponse</code>
 */
class ListTransferJobsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * A list of transfer jobs.
     * </pre>
     *
     * <code>repeated .google.storagetransfer.v1.TransferJob transfer_jobs = 1;</code>
     */
    private $transfer_jobs;
    /**
     * <pre>
     * The list next page token.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    private $next_page_token = '';

    public function __construct() {
        \GPBMetadata\Google\Storagetransfer\V1\Transfer::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * A list of transfer jobs.
     * </pre>
     *
     * <code>repeated .google.storagetransfer.v1.TransferJob transfer_jobs = 1;</code>
     */
    public function getTransferJobs()
    {
        return $this->transfer_jobs;
    }

    /**
     * <pre>
     * A list of transfer jobs.
     * </pre>
     *
     * <code>repeated .google.storagetransfer.v1.TransferJob transfer_jobs = 1;</code>
     */
    public function setTransferJobs(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Storagetransfer\V1\TransferJob::class);
        $this->transfer_jobs = $var;
    }

    /**
     * <pre>
     * The list next page token.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * <pre>
     * The list next page token.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;
    }

}

