<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/storagetransfer/v1/transfer_types.proto

namespace Google\Storagetransfer\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * This resource represents the configuration of a transfer job that runs
 * periodically.
 * </pre>
 *
 * Protobuf type <code>google.storagetransfer.v1.TransferJob</code>
 */
class TransferJob extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * A globally unique name assigned by Storage Transfer Service when the
     * job is created. This field should be left empty in requests to create a new
     * transfer job; otherwise, the requests result in an `INVALID_ARGUMENT`
     * error.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * A description provided by the user for the job. Its max length is 1024
     * bytes when Unicode-encoded.
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    private $description = '';
    /**
     * <pre>
     * The ID of the Google Cloud Platform Console project that owns the job.
     * Required.
     * </pre>
     *
     * <code>string project_id = 3;</code>
     */
    private $project_id = '';
    /**
     * <pre>
     * Transfer specification.
     * Required.
     * </pre>
     *
     * <code>.google.storagetransfer.v1.TransferSpec transfer_spec = 4;</code>
     */
    private $transfer_spec = null;
    /**
     * <pre>
     * Schedule specification.
     * Required.
     * </pre>
     *
     * <code>.google.storagetransfer.v1.Schedule schedule = 5;</code>
     */
    private $schedule = null;
    /**
     * <pre>
     * Status of the job. This value MUST be specified for
     * `CreateTransferJobRequests`.
     * NOTE: The effect of the new job status takes place during a subsequent job
     * run. For example, if you change the job status from `ENABLED` to
     * `DISABLED`, and an operation spawned by the transfer is running, the status
     * change would not affect the current operation.
     * </pre>
     *
     * <code>.google.storagetransfer.v1.TransferJob.Status status = 6;</code>
     */
    private $status = 0;
    /**
     * <pre>
     * This field cannot be changed by user requests.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp creation_time = 7;</code>
     */
    private $creation_time = null;
    /**
     * <pre>
     * This field cannot be changed by user requests.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_modification_time = 8;</code>
     */
    private $last_modification_time = null;
    /**
     * <pre>
     * This field cannot be changed by user requests.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp deletion_time = 9;</code>
     */
    private $deletion_time = null;

    public function __construct() {
        \GPBMetadata\Google\Storagetransfer\V1\TransferTypes::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * A globally unique name assigned by Storage Transfer Service when the
     * job is created. This field should be left empty in requests to create a new
     * transfer job; otherwise, the requests result in an `INVALID_ARGUMENT`
     * error.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * A globally unique name assigned by Storage Transfer Service when the
     * job is created. This field should be left empty in requests to create a new
     * transfer job; otherwise, the requests result in an `INVALID_ARGUMENT`
     * error.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * A description provided by the user for the job. Its max length is 1024
     * bytes when Unicode-encoded.
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * <pre>
     * A description provided by the user for the job. Its max length is 1024
     * bytes when Unicode-encoded.
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

    /**
     * <pre>
     * The ID of the Google Cloud Platform Console project that owns the job.
     * Required.
     * </pre>
     *
     * <code>string project_id = 3;</code>
     */
    public function getProjectId()
    {
        return $this->project_id;
    }

    /**
     * <pre>
     * The ID of the Google Cloud Platform Console project that owns the job.
     * Required.
     * </pre>
     *
     * <code>string project_id = 3;</code>
     */
    public function setProjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_id = $var;
    }

    /**
     * <pre>
     * Transfer specification.
     * Required.
     * </pre>
     *
     * <code>.google.storagetransfer.v1.TransferSpec transfer_spec = 4;</code>
     */
    public function getTransferSpec()
    {
        return $this->transfer_spec;
    }

    /**
     * <pre>
     * Transfer specification.
     * Required.
     * </pre>
     *
     * <code>.google.storagetransfer.v1.TransferSpec transfer_spec = 4;</code>
     */
    public function setTransferSpec(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Storagetransfer\V1\TransferSpec::class);
        $this->transfer_spec = $var;
    }

    /**
     * <pre>
     * Schedule specification.
     * Required.
     * </pre>
     *
     * <code>.google.storagetransfer.v1.Schedule schedule = 5;</code>
     */
    public function getSchedule()
    {
        return $this->schedule;
    }

    /**
     * <pre>
     * Schedule specification.
     * Required.
     * </pre>
     *
     * <code>.google.storagetransfer.v1.Schedule schedule = 5;</code>
     */
    public function setSchedule(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Storagetransfer\V1\Schedule::class);
        $this->schedule = $var;
    }

    /**
     * <pre>
     * Status of the job. This value MUST be specified for
     * `CreateTransferJobRequests`.
     * NOTE: The effect of the new job status takes place during a subsequent job
     * run. For example, if you change the job status from `ENABLED` to
     * `DISABLED`, and an operation spawned by the transfer is running, the status
     * change would not affect the current operation.
     * </pre>
     *
     * <code>.google.storagetransfer.v1.TransferJob.Status status = 6;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     * Status of the job. This value MUST be specified for
     * `CreateTransferJobRequests`.
     * NOTE: The effect of the new job status takes place during a subsequent job
     * run. For example, if you change the job status from `ENABLED` to
     * `DISABLED`, and an operation spawned by the transfer is running, the status
     * change would not affect the current operation.
     * </pre>
     *
     * <code>.google.storagetransfer.v1.TransferJob.Status status = 6;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Google\Storagetransfer\V1\TransferJob_Status::class);
        $this->status = $var;
    }

    /**
     * <pre>
     * This field cannot be changed by user requests.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp creation_time = 7;</code>
     */
    public function getCreationTime()
    {
        return $this->creation_time;
    }

    /**
     * <pre>
     * This field cannot be changed by user requests.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp creation_time = 7;</code>
     */
    public function setCreationTime(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->creation_time = $var;
    }

    /**
     * <pre>
     * This field cannot be changed by user requests.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_modification_time = 8;</code>
     */
    public function getLastModificationTime()
    {
        return $this->last_modification_time;
    }

    /**
     * <pre>
     * This field cannot be changed by user requests.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_modification_time = 8;</code>
     */
    public function setLastModificationTime(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->last_modification_time = $var;
    }

    /**
     * <pre>
     * This field cannot be changed by user requests.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp deletion_time = 9;</code>
     */
    public function getDeletionTime()
    {
        return $this->deletion_time;
    }

    /**
     * <pre>
     * This field cannot be changed by user requests.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp deletion_time = 9;</code>
     */
    public function setDeletionTime(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->deletion_time = $var;
    }

}

