<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dataproc/v1/clusters.proto

namespace Google\Cloud\Dataproc\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Describes the identifying information, config, and status of
 * a cluster of Google Compute Engine instances.
 * </pre>
 *
 * Protobuf type <code>google.cloud.dataproc.v1.Cluster</code>
 */
class Cluster extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * [Required] The Google Cloud Platform project ID that the cluster belongs to.
     * </pre>
     *
     * <code>string project_id = 1;</code>
     */
    private $project_id = '';
    /**
     * <pre>
     * [Required] The cluster name. Cluster names within a project must be
     * unique. Names of deleted clusters can be reused.
     * </pre>
     *
     * <code>string cluster_name = 2;</code>
     */
    private $cluster_name = '';
    /**
     * <pre>
     * [Required] The cluster config. Note that Cloud Dataproc may set
     * default values, and values may change when clusters are updated.
     * </pre>
     *
     * <code>.google.cloud.dataproc.v1.ClusterConfig config = 3;</code>
     */
    private $config = null;
    /**
     * <pre>
     * [Output-only] Cluster status.
     * </pre>
     *
     * <code>.google.cloud.dataproc.v1.ClusterStatus status = 4;</code>
     */
    private $status = null;
    /**
     * <pre>
     * [Output-only] The previous cluster status.
     * </pre>
     *
     * <code>repeated .google.cloud.dataproc.v1.ClusterStatus status_history = 7;</code>
     */
    private $status_history;
    /**
     * <pre>
     * [Output-only] A cluster UUID (Unique Universal Identifier). Cloud Dataproc
     * generates this value when it creates the cluster.
     * </pre>
     *
     * <code>string cluster_uuid = 6;</code>
     */
    private $cluster_uuid = '';

    public function __construct() {
        \GPBMetadata\Google\Cloud\Dataproc\V1\Clusters::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * [Required] The Google Cloud Platform project ID that the cluster belongs to.
     * </pre>
     *
     * <code>string project_id = 1;</code>
     */
    public function getProjectId()
    {
        return $this->project_id;
    }

    /**
     * <pre>
     * [Required] The Google Cloud Platform project ID that the cluster belongs to.
     * </pre>
     *
     * <code>string project_id = 1;</code>
     */
    public function setProjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_id = $var;
    }

    /**
     * <pre>
     * [Required] The cluster name. Cluster names within a project must be
     * unique. Names of deleted clusters can be reused.
     * </pre>
     *
     * <code>string cluster_name = 2;</code>
     */
    public function getClusterName()
    {
        return $this->cluster_name;
    }

    /**
     * <pre>
     * [Required] The cluster name. Cluster names within a project must be
     * unique. Names of deleted clusters can be reused.
     * </pre>
     *
     * <code>string cluster_name = 2;</code>
     */
    public function setClusterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->cluster_name = $var;
    }

    /**
     * <pre>
     * [Required] The cluster config. Note that Cloud Dataproc may set
     * default values, and values may change when clusters are updated.
     * </pre>
     *
     * <code>.google.cloud.dataproc.v1.ClusterConfig config = 3;</code>
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * <pre>
     * [Required] The cluster config. Note that Cloud Dataproc may set
     * default values, and values may change when clusters are updated.
     * </pre>
     *
     * <code>.google.cloud.dataproc.v1.ClusterConfig config = 3;</code>
     */
    public function setConfig(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Dataproc\V1\ClusterConfig::class);
        $this->config = $var;
    }

    /**
     * <pre>
     * [Output-only] Cluster status.
     * </pre>
     *
     * <code>.google.cloud.dataproc.v1.ClusterStatus status = 4;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     * [Output-only] Cluster status.
     * </pre>
     *
     * <code>.google.cloud.dataproc.v1.ClusterStatus status = 4;</code>
     */
    public function setStatus(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Dataproc\V1\ClusterStatus::class);
        $this->status = $var;
    }

    /**
     * <pre>
     * [Output-only] The previous cluster status.
     * </pre>
     *
     * <code>repeated .google.cloud.dataproc.v1.ClusterStatus status_history = 7;</code>
     */
    public function getStatusHistory()
    {
        return $this->status_history;
    }

    /**
     * <pre>
     * [Output-only] The previous cluster status.
     * </pre>
     *
     * <code>repeated .google.cloud.dataproc.v1.ClusterStatus status_history = 7;</code>
     */
    public function setStatusHistory(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Dataproc\V1\ClusterStatus::class);
        $this->status_history = $var;
    }

    /**
     * <pre>
     * [Output-only] A cluster UUID (Unique Universal Identifier). Cloud Dataproc
     * generates this value when it creates the cluster.
     * </pre>
     *
     * <code>string cluster_uuid = 6;</code>
     */
    public function getClusterUuid()
    {
        return $this->cluster_uuid;
    }

    /**
     * <pre>
     * [Output-only] A cluster UUID (Unique Universal Identifier). Cloud Dataproc
     * generates this value when it creates the cluster.
     * </pre>
     *
     * <code>string cluster_uuid = 6;</code>
     */
    public function setClusterUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->cluster_uuid = $var;
    }

}

