<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dataproc/v1/clusters.proto

namespace Google\Cloud\Dataproc\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * A request to collect cluster diagnostic information.
 * </pre>
 *
 * Protobuf type <code>google.cloud.dataproc.v1.DiagnoseClusterRequest</code>
 */
class DiagnoseClusterRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * [Required] The ID of the Google Cloud Platform project that the cluster
     * belongs to.
     * </pre>
     *
     * <code>string project_id = 1;</code>
     */
    private $project_id = '';
    /**
     * <pre>
     * [Required] The Cloud Dataproc region in which to handle the request.
     * </pre>
     *
     * <code>string region = 3;</code>
     */
    private $region = '';
    /**
     * <pre>
     * [Required] The cluster name.
     * </pre>
     *
     * <code>string cluster_name = 2;</code>
     */
    private $cluster_name = '';

    public function __construct() {
        \GPBMetadata\Google\Cloud\Dataproc\V1\Clusters::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * [Required] The ID of the Google Cloud Platform project that the cluster
     * belongs to.
     * </pre>
     *
     * <code>string project_id = 1;</code>
     */
    public function getProjectId()
    {
        return $this->project_id;
    }

    /**
     * <pre>
     * [Required] The ID of the Google Cloud Platform project that the cluster
     * belongs to.
     * </pre>
     *
     * <code>string project_id = 1;</code>
     */
    public function setProjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_id = $var;
    }

    /**
     * <pre>
     * [Required] The Cloud Dataproc region in which to handle the request.
     * </pre>
     *
     * <code>string region = 3;</code>
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * <pre>
     * [Required] The Cloud Dataproc region in which to handle the request.
     * </pre>
     *
     * <code>string region = 3;</code>
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->region = $var;
    }

    /**
     * <pre>
     * [Required] The cluster name.
     * </pre>
     *
     * <code>string cluster_name = 2;</code>
     */
    public function getClusterName()
    {
        return $this->cluster_name;
    }

    /**
     * <pre>
     * [Required] The cluster name.
     * </pre>
     *
     * <code>string cluster_name = 2;</code>
     */
    public function setClusterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->cluster_name = $var;
    }

}

