<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/support/common.proto

namespace Google\Cloud\Support\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Represents the product component taxonomy that is to be used while creating
 * or updating a `Case`. A client should obtain the list of issue categories,
 * component/subcomponent from this object and specify it in `Case.category`,
 * `Case.component` and `Case.subcomponent` fields respectively.
 * </pre>
 *
 * Protobuf type <code>google.cloud.support.common.IssueTaxonomy</code>
 */
class IssueTaxonomy extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Map of available categories.
     * </pre>
     *
     * <code>map&lt;string, .google.cloud.support.common.IssueTaxonomy.Category&gt; categories = 1;</code>
     */
    private $categories;

    public function __construct() {
        \GPBMetadata\Google\Cloud\Support\Common::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Map of available categories.
     * </pre>
     *
     * <code>map&lt;string, .google.cloud.support.common.IssueTaxonomy.Category&gt; categories = 1;</code>
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * <pre>
     * Map of available categories.
     * </pre>
     *
     * <code>map&lt;string, .google.cloud.support.common.IssueTaxonomy.Category&gt; categories = 1;</code>
     */
    public function setCategories(&$var)
    {
        $this->categories = $var;
    }

}

