<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/bigtable/admin/v2/instance.proto

namespace Google\Bigtable\Admin\V2;

/**
 * <pre>
 * The type of the instance.
 * </pre>
 *
 * Protobuf enum <code>google.bigtable.admin.v2.Instance.Type</code>
 */
class Instance_Type
{
    /**
     * <pre>
     * The type of the instance is unspecified. If set when creating an
     * instance, a `PRODUCTION` instance will be created. If set when updating
     * an instance, the type will be left unchanged.
     * </pre>
     *
     * <code>TYPE_UNSPECIFIED = 0;</code>
     */
    const TYPE_UNSPECIFIED = 0;
    /**
     * <pre>
     * An instance meant for production use. `serve_nodes` must be set
     * on the cluster.
     * </pre>
     *
     * <code>PRODUCTION = 1;</code>
     */
    const PRODUCTION = 1;
}

