<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/watcher/v1/watch.proto

namespace Google\Watcher\V1;

/**
 * <pre>
 * A reported value can be in one of the following states:
 * </pre>
 *
 * Protobuf enum <code>google.watcher.v1.Change.State</code>
 */
class Change_State
{
    /**
     * <pre>
     * The element exists and its full value is included in data.
     * </pre>
     *
     * <code>EXISTS = 0;</code>
     */
    const EXISTS = 0;
    /**
     * <pre>
     * The element does not exist.
     * </pre>
     *
     * <code>DOES_NOT_EXIST = 1;</code>
     */
    const DOES_NOT_EXIST = 1;
    /**
     * <pre>
     * Element may or may not exist. Used only for initial state delivery when
     * the client is not interested in fetching the initial state. See the
     * "Initial State" section above.
     * </pre>
     *
     * <code>INITIAL_STATE_SKIPPED = 2;</code>
     */
    const INITIAL_STATE_SKIPPED = 2;
    /**
     * <pre>
     * The element may exist, but some error has occurred. More information is
     * available in the data field - the value is a serialized Status
     * proto (from [google.rpc.Status][])
     * </pre>
     *
     * <code>ERROR = 3;</code>
     */
    const ERROR = 3;
}

