<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/assistant/embedded/v1alpha1/embedded_assistant.proto

namespace Google\Assistant\Embedded\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Specifies how to process the `audio_in` data that will be provided in
 * subsequent requests. For recommended settings, see the Google Assistant SDK
 * [best practices](https://developers.google.com/assistant/best-practices).
 * </pre>
 *
 * Protobuf type <code>google.assistant.embedded.v1alpha1.AudioInConfig</code>
 */
class AudioInConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * *Required* Encoding of audio data sent in all `audio_in` messages.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha1.AudioInConfig.Encoding encoding = 1;</code>
     */
    private $encoding = 0;
    /**
     * <pre>
     * *Required* Sample rate (in Hertz) of the audio data sent in all `audio_in`
     * messages. Valid values are from 16000-24000, but 16000 is optimal.
     * For best results, set the sampling rate of the audio source to 16000 Hz.
     * If that's not possible, use the native sample rate of the audio source
     * (instead of re-sampling).
     * </pre>
     *
     * <code>int32 sample_rate_hertz = 2;</code>
     */
    private $sample_rate_hertz = 0;

    public function __construct() {
        \GPBMetadata\Google\Assistant\Embedded\V1Alpha1\EmbeddedAssistant::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * *Required* Encoding of audio data sent in all `audio_in` messages.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha1.AudioInConfig.Encoding encoding = 1;</code>
     */
    public function getEncoding()
    {
        return $this->encoding;
    }

    /**
     * <pre>
     * *Required* Encoding of audio data sent in all `audio_in` messages.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha1.AudioInConfig.Encoding encoding = 1;</code>
     */
    public function setEncoding($var)
    {
        GPBUtil::checkEnum($var, \Google\Assistant\Embedded\V1alpha1\AudioInConfig_Encoding::class);
        $this->encoding = $var;
    }

    /**
     * <pre>
     * *Required* Sample rate (in Hertz) of the audio data sent in all `audio_in`
     * messages. Valid values are from 16000-24000, but 16000 is optimal.
     * For best results, set the sampling rate of the audio source to 16000 Hz.
     * If that's not possible, use the native sample rate of the audio source
     * (instead of re-sampling).
     * </pre>
     *
     * <code>int32 sample_rate_hertz = 2;</code>
     */
    public function getSampleRateHertz()
    {
        return $this->sample_rate_hertz;
    }

    /**
     * <pre>
     * *Required* Sample rate (in Hertz) of the audio data sent in all `audio_in`
     * messages. Valid values are from 16000-24000, but 16000 is optimal.
     * For best results, set the sampling rate of the audio source to 16000 Hz.
     * If that's not possible, use the native sample rate of the audio source
     * (instead of re-sampling).
     * </pre>
     *
     * <code>int32 sample_rate_hertz = 2;</code>
     */
    public function setSampleRateHertz($var)
    {
        GPBUtil::checkInt32($var);
        $this->sample_rate_hertz = $var;
    }

}

