<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/assistant/embedded/v1alpha1/embedded_assistant.proto

namespace Google\Assistant\Embedded\V1alpha1;

/**
 * <pre>
 * Indicates the type of event.
 * </pre>
 *
 * Protobuf enum <code>google.assistant.embedded.v1alpha1.ConverseResponse.EventType</code>
 */
class ConverseResponse_EventType
{
    /**
     * <pre>
     * No event specified.
     * </pre>
     *
     * <code>EVENT_TYPE_UNSPECIFIED = 0;</code>
     */
    const EVENT_TYPE_UNSPECIFIED = 0;
    /**
     * <pre>
     * This event indicates that the server has detected the end of the user's
     * speech utterance and expects no additional speech. Therefore, the server
     * will not process additional audio (although it may subsequently return
     * additional results). The client should stop sending additional audio
     * data, half-close the gRPC connection, and wait for any additional results
     * until the server closes the gRPC connection.
     * </pre>
     *
     * <code>END_OF_UTTERANCE = 1;</code>
     */
    const END_OF_UTTERANCE = 1;
}

