<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/cloudbuild/v1/cloudbuild.proto

namespace Google\Devtools\Cloudbuild\V1;

/**
 * <pre>
 * Specifies the manner in which the build should be verified, if at all.
 * </pre>
 *
 * Protobuf enum <code>google.devtools.cloudbuild.v1.BuildOptions.VerifyOption</code>
 */
class BuildOptions_VerifyOption
{
    /**
     * <pre>
     * Not a verifiable build. (default)
     * </pre>
     *
     * <code>NOT_VERIFIED = 0;</code>
     */
    const NOT_VERIFIED = 0;
    /**
     * <pre>
     * Verified build.
     * </pre>
     *
     * <code>VERIFIED = 1;</code>
     */
    const VERIFIED = 1;
}

