<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/ml/v1/job_service.proto

namespace Google\Cloud\Ml\V1;

/**
 * <pre>
 * The format used to separate data instances in the source files.
 * </pre>
 *
 * Protobuf enum <code>google.cloud.ml.v1.PredictionInput.DataFormat</code>
 */
class PredictionInput_DataFormat
{
    /**
     * <pre>
     * Unspecified format.
     * </pre>
     *
     * <code>DATA_FORMAT_UNSPECIFIED = 0;</code>
     */
    const DATA_FORMAT_UNSPECIFIED = 0;
    /**
     * <pre>
     * The source file is a text file with instances separated by the
     * new-line character.
     * </pre>
     *
     * <code>TEXT = 1;</code>
     */
    const TEXT = 1;
    /**
     * <pre>
     * The source file is a TFRecord file.
     * </pre>
     *
     * <code>TF_RECORD = 2;</code>
     */
    const TF_RECORD = 2;
    /**
     * <pre>
     * The source file is a GZIP-compressed TFRecord file.
     * </pre>
     *
     * <code>TF_RECORD_GZIP = 3;</code>
     */
    const TF_RECORD_GZIP = 3;
}

