<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/ml/v1beta1/project_service.proto

namespace Google\Cloud\Ml\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Returns service account information associated with a project.
 * </pre>
 *
 * Protobuf type <code>google.cloud.ml.v1beta1.GetConfigResponse</code>
 */
class GetConfigResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The service account Cloud ML uses to access resources in the project.
     * </pre>
     *
     * <code>string service_account = 1;</code>
     */
    private $service_account = '';
    /**
     * <pre>
     * The project number for `service_account`.
     * </pre>
     *
     * <code>int64 service_account_project = 2;</code>
     */
    private $service_account_project = 0;

    public function __construct() {
        \GPBMetadata\Google\Cloud\Ml\V1Beta1\ProjectService::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The service account Cloud ML uses to access resources in the project.
     * </pre>
     *
     * <code>string service_account = 1;</code>
     */
    public function getServiceAccount()
    {
        return $this->service_account;
    }

    /**
     * <pre>
     * The service account Cloud ML uses to access resources in the project.
     * </pre>
     *
     * <code>string service_account = 1;</code>
     */
    public function setServiceAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_account = $var;
    }

    /**
     * <pre>
     * The project number for `service_account`.
     * </pre>
     *
     * <code>int64 service_account_project = 2;</code>
     */
    public function getServiceAccountProject()
    {
        return $this->service_account_project;
    }

    /**
     * <pre>
     * The project number for `service_account`.
     * </pre>
     *
     * <code>int64 service_account_project = 2;</code>
     */
    public function setServiceAccountProject($var)
    {
        GPBUtil::checkInt64($var);
        $this->service_account_project = $var;
    }

}

