<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/ml/v1beta1/job_service.proto

namespace Google\Cloud\Ml\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * An observed value of a metric.
 * </pre>
 *
 * Protobuf type <code>google.cloud.ml.v1beta1.HyperparameterOutput.HyperparameterMetric</code>
 */
class HyperparameterOutput_HyperparameterMetric extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The global training step for this metric.
     * </pre>
     *
     * <code>int64 training_step = 1;</code>
     */
    private $training_step = 0;
    /**
     * <pre>
     * The objective value at this training step.
     * </pre>
     *
     * <code>double objective_value = 2;</code>
     */
    private $objective_value = 0.0;

    public function __construct() {
        \GPBMetadata\Google\Cloud\Ml\V1Beta1\JobService::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The global training step for this metric.
     * </pre>
     *
     * <code>int64 training_step = 1;</code>
     */
    public function getTrainingStep()
    {
        return $this->training_step;
    }

    /**
     * <pre>
     * The global training step for this metric.
     * </pre>
     *
     * <code>int64 training_step = 1;</code>
     */
    public function setTrainingStep($var)
    {
        GPBUtil::checkInt64($var);
        $this->training_step = $var;
    }

    /**
     * <pre>
     * The objective value at this training step.
     * </pre>
     *
     * <code>double objective_value = 2;</code>
     */
    public function getObjectiveValue()
    {
        return $this->objective_value;
    }

    /**
     * <pre>
     * The objective value at this training step.
     * </pre>
     *
     * <code>double objective_value = 2;</code>
     */
    public function setObjectiveValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->objective_value = $var;
    }

}

