<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/ml/v1beta1/model_service.proto

namespace Google\Cloud\Ml\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response message for the ListVersions method.
 * </pre>
 *
 * Protobuf type <code>google.cloud.ml.v1beta1.ListVersionsResponse</code>
 */
class ListVersionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The list of versions.
     * </pre>
     *
     * <code>repeated .google.cloud.ml.v1beta1.Version versions = 1;</code>
     */
    private $versions;
    /**
     * <pre>
     * Optional. Pass this token as the `page_token` field of the request for a
     * subsequent call.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    private $next_page_token = '';

    public function __construct() {
        \GPBMetadata\Google\Cloud\Ml\V1Beta1\ModelService::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The list of versions.
     * </pre>
     *
     * <code>repeated .google.cloud.ml.v1beta1.Version versions = 1;</code>
     */
    public function getVersions()
    {
        return $this->versions;
    }

    /**
     * <pre>
     * The list of versions.
     * </pre>
     *
     * <code>repeated .google.cloud.ml.v1beta1.Version versions = 1;</code>
     */
    public function setVersions(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Ml\V1beta1\Version::class);
        $this->versions = $arr;
    }

    /**
     * <pre>
     * Optional. Pass this token as the `page_token` field of the request for a
     * subsequent call.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * <pre>
     * Optional. Pass this token as the `page_token` field of the request for a
     * subsequent call.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;
    }

}

