<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/billing/v1/cloud_billing.proto

namespace Google\Cloud\Billing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request message for `ListProjectBillingInfoResponse`.
 * </pre>
 *
 * Protobuf type <code>google.cloud.billing.v1.ListProjectBillingInfoResponse</code>
 */
class ListProjectBillingInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * A list of `ProjectBillingInfo` resources representing the projects
     * associated with the billing account.
     * </pre>
     *
     * <code>repeated .google.cloud.billing.v1.ProjectBillingInfo project_billing_info = 1;</code>
     */
    private $project_billing_info;
    /**
     * <pre>
     * A token to retrieve the next page of results. To retrieve the next page,
     * call `ListProjectBillingInfo` again with the `page_token` field set to this
     * value. This field is empty if there are no more results to retrieve.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    private $next_page_token = '';

    public function __construct() {
        \GPBMetadata\Google\Cloud\Billing\V1\CloudBilling::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * A list of `ProjectBillingInfo` resources representing the projects
     * associated with the billing account.
     * </pre>
     *
     * <code>repeated .google.cloud.billing.v1.ProjectBillingInfo project_billing_info = 1;</code>
     */
    public function getProjectBillingInfo()
    {
        return $this->project_billing_info;
    }

    /**
     * <pre>
     * A list of `ProjectBillingInfo` resources representing the projects
     * associated with the billing account.
     * </pre>
     *
     * <code>repeated .google.cloud.billing.v1.ProjectBillingInfo project_billing_info = 1;</code>
     */
    public function setProjectBillingInfo(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Billing\V1\ProjectBillingInfo::class);
        $this->project_billing_info = $var;
    }

    /**
     * <pre>
     * A token to retrieve the next page of results. To retrieve the next page,
     * call `ListProjectBillingInfo` again with the `page_token` field set to this
     * value. This field is empty if there are no more results to retrieve.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * <pre>
     * A token to retrieve the next page of results. To retrieve the next page,
     * call `ListProjectBillingInfo` again with the `page_token` field set to this
     * value. This field is empty if there are no more results to retrieve.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;
    }

}

