<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/billing/v1/cloud_billing.proto

namespace Google\Cloud\Billing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response message for `ListBillingAccounts`.
 * </pre>
 *
 * Protobuf type <code>google.cloud.billing.v1.ListBillingAccountsResponse</code>
 */
class ListBillingAccountsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * A list of billing accounts.
     * </pre>
     *
     * <code>repeated .google.cloud.billing.v1.BillingAccount billing_accounts = 1;</code>
     */
    private $billing_accounts;
    /**
     * <pre>
     * A token to retrieve the next page of results. To retrieve the next page,
     * call `ListBillingAccounts` again with the `page_token` field set to this
     * value. This field is empty if there are no more results to retrieve.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    private $next_page_token = '';

    public function __construct() {
        \GPBMetadata\Google\Cloud\Billing\V1\CloudBilling::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * A list of billing accounts.
     * </pre>
     *
     * <code>repeated .google.cloud.billing.v1.BillingAccount billing_accounts = 1;</code>
     */
    public function getBillingAccounts()
    {
        return $this->billing_accounts;
    }

    /**
     * <pre>
     * A list of billing accounts.
     * </pre>
     *
     * <code>repeated .google.cloud.billing.v1.BillingAccount billing_accounts = 1;</code>
     */
    public function setBillingAccounts(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Billing\V1\BillingAccount::class);
        $this->billing_accounts = $var;
    }

    /**
     * <pre>
     * A token to retrieve the next page of results. To retrieve the next page,
     * call `ListBillingAccounts` again with the `page_token` field set to this
     * value. This field is empty if there are no more results to retrieve.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * <pre>
     * A token to retrieve the next page of results. To retrieve the next page,
     * call `ListBillingAccounts` again with the `page_token` field set to this
     * value. This field is empty if there are no more results to retrieve.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;
    }

}

