<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/appengine/v1/appengine.proto

namespace Google\Appengine\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request message for `Versions.ListVersions`.
 * </pre>
 *
 * Protobuf type <code>google.appengine.v1.ListVersionsRequest</code>
 */
class ListVersionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Name of the parent Service resource. Example:
     * `apps/myapp/services/default`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    private $parent = '';
    /**
     * <pre>
     * Controls the set of fields returned in the `List` response.
     * </pre>
     *
     * <code>.google.appengine.v1.VersionView view = 2;</code>
     */
    private $view = 0;
    /**
     * <pre>
     * Maximum results to return per page.
     * </pre>
     *
     * <code>int32 page_size = 3;</code>
     */
    private $page_size = 0;
    /**
     * <pre>
     * Continuation token for fetching the next page of results.
     * </pre>
     *
     * <code>string page_token = 4;</code>
     */
    private $page_token = '';

    public function __construct() {
        \GPBMetadata\Google\Appengine\V1\Appengine::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Name of the parent Service resource. Example:
     * `apps/myapp/services/default`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * <pre>
     * Name of the parent Service resource. Example:
     * `apps/myapp/services/default`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;
    }

    /**
     * <pre>
     * Controls the set of fields returned in the `List` response.
     * </pre>
     *
     * <code>.google.appengine.v1.VersionView view = 2;</code>
     */
    public function getView()
    {
        return $this->view;
    }

    /**
     * <pre>
     * Controls the set of fields returned in the `List` response.
     * </pre>
     *
     * <code>.google.appengine.v1.VersionView view = 2;</code>
     */
    public function setView($var)
    {
        GPBUtil::checkEnum($var, \Google\Appengine\V1\VersionView::class);
        $this->view = $var;
    }

    /**
     * <pre>
     * Maximum results to return per page.
     * </pre>
     *
     * <code>int32 page_size = 3;</code>
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * <pre>
     * Maximum results to return per page.
     * </pre>
     *
     * <code>int32 page_size = 3;</code>
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;
    }

    /**
     * <pre>
     * Continuation token for fetching the next page of results.
     * </pre>
     *
     * <code>string page_token = 4;</code>
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * <pre>
     * Continuation token for fetching the next page of results.
     * </pre>
     *
     * <code>string page_token = 4;</code>
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;
    }

}

