<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/appengine/v1/version.proto

namespace Google\Appengine\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * A service with manual scaling runs continuously, allowing you to perform
 * complex initialization and rely on the state of its memory over time.
 * </pre>
 *
 * Protobuf type <code>google.appengine.v1.ManualScaling</code>
 */
class ManualScaling extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Number of instances to assign to the service at the start. This number
     * can later be altered by using the
     * [Modules API](https://cloud.google.com/appengine/docs/python/modules/functions)
     * `set_num_instances()` function.
     * </pre>
     *
     * <code>int32 instances = 1;</code>
     */
    private $instances = 0;

    public function __construct() {
        \GPBMetadata\Google\Appengine\V1\Version::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Number of instances to assign to the service at the start. This number
     * can later be altered by using the
     * [Modules API](https://cloud.google.com/appengine/docs/python/modules/functions)
     * `set_num_instances()` function.
     * </pre>
     *
     * <code>int32 instances = 1;</code>
     */
    public function getInstances()
    {
        return $this->instances;
    }

    /**
     * <pre>
     * Number of instances to assign to the service at the start. This number
     * can later be altered by using the
     * [Modules API](https://cloud.google.com/appengine/docs/python/modules/functions)
     * `set_num_instances()` function.
     * </pre>
     *
     * <code>int32 instances = 1;</code>
     */
    public function setInstances($var)
    {
        GPBUtil::checkInt32($var);
        $this->instances = $var;
    }

}

