<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/appengine/v1/appengine.proto

namespace Google\Appengine\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request message for `Versions.UpdateVersion`.
 * </pre>
 *
 * Protobuf type <code>google.appengine.v1.UpdateVersionRequest</code>
 */
class UpdateVersionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Name of the resource to update. Example:
     * `apps/myapp/services/default/versions/1`.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * A Version containing the updated resource. Only fields set in the field
     * mask will be updated.
     * </pre>
     *
     * <code>.google.appengine.v1.Version version = 2;</code>
     */
    private $version = null;
    /**
     * <pre>
     * Standard field mask for the set of fields to be updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    private $update_mask = null;

    public function __construct() {
        \GPBMetadata\Google\Appengine\V1\Appengine::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Name of the resource to update. Example:
     * `apps/myapp/services/default/versions/1`.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * Name of the resource to update. Example:
     * `apps/myapp/services/default/versions/1`.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * A Version containing the updated resource. Only fields set in the field
     * mask will be updated.
     * </pre>
     *
     * <code>.google.appengine.v1.Version version = 2;</code>
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * <pre>
     * A Version containing the updated resource. Only fields set in the field
     * mask will be updated.
     * </pre>
     *
     * <code>.google.appengine.v1.Version version = 2;</code>
     */
    public function setVersion(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Appengine\V1\Version::class);
        $this->version = $var;
    }

    /**
     * <pre>
     * Standard field mask for the set of fields to be updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    /**
     * <pre>
     * Standard field mask for the set of fields to be updated.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 3;</code>
     */
    public function setUpdateMask(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;
    }

}

