<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1alpha2/pipelines.proto

namespace Google\Genomics\V1alpha2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * The request to create a pipeline. The pipeline field here should not have
 * `pipelineId` populated, as that will be populated by the server.
 * </pre>
 *
 * Protobuf type <code>google.genomics.v1alpha2.CreatePipelineRequest</code>
 */
class CreatePipelineRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The pipeline to create. Should not have `pipelineId` populated.
     * </pre>
     *
     * <code>.google.genomics.v1alpha2.Pipeline pipeline = 1;</code>
     */
    private $pipeline = null;

    public function __construct() {
        \GPBMetadata\Google\Genomics\V1Alpha2\Pipelines::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The pipeline to create. Should not have `pipelineId` populated.
     * </pre>
     *
     * <code>.google.genomics.v1alpha2.Pipeline pipeline = 1;</code>
     */
    public function getPipeline()
    {
        return $this->pipeline;
    }

    /**
     * <pre>
     * The pipeline to create. Should not have `pipelineId` populated.
     * </pre>
     *
     * <code>.google.genomics.v1alpha2.Pipeline pipeline = 1;</code>
     */
    public function setPipeline(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Genomics\V1alpha2\Pipeline::class);
        $this->pipeline = $var;
    }

}

