<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/appengine/logging/v1/request_log.proto

namespace Google\Appengine\Logging\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Complete log information about a single HTTP request to an App Engine
 * application.
 * </pre>
 *
 * Protobuf type <code>google.appengine.logging.v1.RequestLog</code>
 */
class RequestLog extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Application that handled this request.
     * </pre>
     *
     * <code>string app_id = 1;</code>
     */
    private $app_id = '';
    /**
     * <pre>
     * Module of the application that handled this request.
     * </pre>
     *
     * <code>string module_id = 37;</code>
     */
    private $module_id = '';
    /**
     * <pre>
     * Version of the application that handled this request.
     * </pre>
     *
     * <code>string version_id = 2;</code>
     */
    private $version_id = '';
    /**
     * <pre>
     * Globally unique identifier for a request, which is based on the request
     * start time.  Request IDs for requests which started later will compare
     * greater as strings than those for requests which started earlier.
     * </pre>
     *
     * <code>string request_id = 3;</code>
     */
    private $request_id = '';
    /**
     * <pre>
     * Origin IP address.
     * </pre>
     *
     * <code>string ip = 4;</code>
     */
    private $ip = '';
    /**
     * <pre>
     * Time when the request started.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_time = 6;</code>
     */
    private $start_time = null;
    /**
     * <pre>
     * Time when the request finished.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_time = 7;</code>
     */
    private $end_time = null;
    /**
     * <pre>
     * Latency of the request.
     * </pre>
     *
     * <code>.google.protobuf.Duration latency = 8;</code>
     */
    private $latency = null;
    /**
     * <pre>
     * Number of CPU megacycles used to process request.
     * </pre>
     *
     * <code>int64 mega_cycles = 9;</code>
     */
    private $mega_cycles = 0;
    /**
     * <pre>
     * Request method. Example: `"GET"`, `"HEAD"`, `"PUT"`, `"POST"`, `"DELETE"`.
     * </pre>
     *
     * <code>string method = 10;</code>
     */
    private $method = '';
    /**
     * <pre>
     * Contains the path and query portion of the URL that was requested. For
     * example, if the URL was "http://example.com/app?name=val", the resource
     * would be "/app?name=val".  The fragment identifier, which is identified by
     * the `#` character, is not included.
     * </pre>
     *
     * <code>string resource = 11;</code>
     */
    private $resource = '';
    /**
     * <pre>
     * HTTP version of request. Example: `"HTTP/1.1"`.
     * </pre>
     *
     * <code>string http_version = 12;</code>
     */
    private $http_version = '';
    /**
     * <pre>
     * HTTP response status code. Example: 200, 404.
     * </pre>
     *
     * <code>int32 status = 13;</code>
     */
    private $status = 0;
    /**
     * <pre>
     * Size in bytes sent back to client by request.
     * </pre>
     *
     * <code>int64 response_size = 14;</code>
     */
    private $response_size = 0;
    /**
     * <pre>
     * Referrer URL of request.
     * </pre>
     *
     * <code>string referrer = 15;</code>
     */
    private $referrer = '';
    /**
     * <pre>
     * User agent that made the request.
     * </pre>
     *
     * <code>string user_agent = 16;</code>
     */
    private $user_agent = '';
    /**
     * <pre>
     * The logged-in user who made the request.
     * Most likely, this is the part of the user's email before the `&#64;` sign.  The
     * field value is the same for different requests from the same user, but
     * different users can have similar names.  This information is also
     * available to the application via the App Engine Users API.
     * This field will be populated starting with App Engine 1.9.21.
     * </pre>
     *
     * <code>string nickname = 40;</code>
     */
    private $nickname = '';
    /**
     * <pre>
     * File or class that handled the request.
     * </pre>
     *
     * <code>string url_map_entry = 17;</code>
     */
    private $url_map_entry = '';
    /**
     * <pre>
     * Internet host and port number of the resource being requested.
     * </pre>
     *
     * <code>string host = 20;</code>
     */
    private $host = '';
    /**
     * <pre>
     * An indication of the relative cost of serving this request.
     * </pre>
     *
     * <code>double cost = 21;</code>
     */
    private $cost = 0.0;
    /**
     * <pre>
     * Queue name of the request, in the case of an offline request.
     * </pre>
     *
     * <code>string task_queue_name = 22;</code>
     */
    private $task_queue_name = '';
    /**
     * <pre>
     * Task name of the request, in the case of an offline request.
     * </pre>
     *
     * <code>string task_name = 23;</code>
     */
    private $task_name = '';
    /**
     * <pre>
     * Whether this was a loading request for the instance.
     * </pre>
     *
     * <code>bool was_loading_request = 24;</code>
     */
    private $was_loading_request = false;
    /**
     * <pre>
     * Time this request spent in the pending request queue.
     * </pre>
     *
     * <code>.google.protobuf.Duration pending_time = 25;</code>
     */
    private $pending_time = null;
    /**
     * <pre>
     * If the instance processing this request belongs to a manually scaled
     * module, then this is the 0-based index of the instance. Otherwise, this
     * value is -1.
     * </pre>
     *
     * <code>int32 instance_index = 26;</code>
     */
    private $instance_index = 0;
    /**
     * <pre>
     * Whether this request is finished or active.
     * </pre>
     *
     * <code>bool finished = 27;</code>
     */
    private $finished = false;
    /**
     * <pre>
     * Whether this is the first `RequestLog` entry for this request.  If an
     * active request has several `RequestLog` entries written to Stackdriver
     * Logging, then this field will be set for one of them.
     * </pre>
     *
     * <code>bool first = 42;</code>
     */
    private $first = false;
    /**
     * <pre>
     * An identifier for the instance that handled the request.
     * </pre>
     *
     * <code>string instance_id = 28;</code>
     */
    private $instance_id = '';
    /**
     * <pre>
     * A list of log lines emitted by the application while serving this request.
     * </pre>
     *
     * <code>repeated .google.appengine.logging.v1.LogLine line = 29;</code>
     */
    private $line;
    /**
     * <pre>
     * App Engine release version.
     * </pre>
     *
     * <code>string app_engine_release = 38;</code>
     */
    private $app_engine_release = '';
    /**
     * <pre>
     * Stackdriver Trace identifier for this request.
     * </pre>
     *
     * <code>string trace_id = 39;</code>
     */
    private $trace_id = '';
    /**
     * <pre>
     * Source code for the application that handled this request. There can be
     * more than one source reference per deployed application if source code is
     * distributed among multiple repositories.
     * </pre>
     *
     * <code>repeated .google.appengine.logging.v1.SourceReference source_reference = 41;</code>
     */
    private $source_reference;

    public function __construct() {
        \GPBMetadata\Google\Appengine\Logging\V1\RequestLog::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Application that handled this request.
     * </pre>
     *
     * <code>string app_id = 1;</code>
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * <pre>
     * Application that handled this request.
     * </pre>
     *
     * <code>string app_id = 1;</code>
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_id = $var;
    }

    /**
     * <pre>
     * Module of the application that handled this request.
     * </pre>
     *
     * <code>string module_id = 37;</code>
     */
    public function getModuleId()
    {
        return $this->module_id;
    }

    /**
     * <pre>
     * Module of the application that handled this request.
     * </pre>
     *
     * <code>string module_id = 37;</code>
     */
    public function setModuleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->module_id = $var;
    }

    /**
     * <pre>
     * Version of the application that handled this request.
     * </pre>
     *
     * <code>string version_id = 2;</code>
     */
    public function getVersionId()
    {
        return $this->version_id;
    }

    /**
     * <pre>
     * Version of the application that handled this request.
     * </pre>
     *
     * <code>string version_id = 2;</code>
     */
    public function setVersionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->version_id = $var;
    }

    /**
     * <pre>
     * Globally unique identifier for a request, which is based on the request
     * start time.  Request IDs for requests which started later will compare
     * greater as strings than those for requests which started earlier.
     * </pre>
     *
     * <code>string request_id = 3;</code>
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * <pre>
     * Globally unique identifier for a request, which is based on the request
     * start time.  Request IDs for requests which started later will compare
     * greater as strings than those for requests which started earlier.
     * </pre>
     *
     * <code>string request_id = 3;</code>
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->request_id = $var;
    }

    /**
     * <pre>
     * Origin IP address.
     * </pre>
     *
     * <code>string ip = 4;</code>
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * <pre>
     * Origin IP address.
     * </pre>
     *
     * <code>string ip = 4;</code>
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;
    }

    /**
     * <pre>
     * Time when the request started.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_time = 6;</code>
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * <pre>
     * Time when the request started.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_time = 6;</code>
     */
    public function setStartTime(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_time = $var;
    }

    /**
     * <pre>
     * Time when the request finished.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_time = 7;</code>
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * <pre>
     * Time when the request finished.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_time = 7;</code>
     */
    public function setEndTime(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->end_time = $var;
    }

    /**
     * <pre>
     * Latency of the request.
     * </pre>
     *
     * <code>.google.protobuf.Duration latency = 8;</code>
     */
    public function getLatency()
    {
        return $this->latency;
    }

    /**
     * <pre>
     * Latency of the request.
     * </pre>
     *
     * <code>.google.protobuf.Duration latency = 8;</code>
     */
    public function setLatency(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->latency = $var;
    }

    /**
     * <pre>
     * Number of CPU megacycles used to process request.
     * </pre>
     *
     * <code>int64 mega_cycles = 9;</code>
     */
    public function getMegaCycles()
    {
        return $this->mega_cycles;
    }

    /**
     * <pre>
     * Number of CPU megacycles used to process request.
     * </pre>
     *
     * <code>int64 mega_cycles = 9;</code>
     */
    public function setMegaCycles($var)
    {
        GPBUtil::checkInt64($var);
        $this->mega_cycles = $var;
    }

    /**
     * <pre>
     * Request method. Example: `"GET"`, `"HEAD"`, `"PUT"`, `"POST"`, `"DELETE"`.
     * </pre>
     *
     * <code>string method = 10;</code>
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * <pre>
     * Request method. Example: `"GET"`, `"HEAD"`, `"PUT"`, `"POST"`, `"DELETE"`.
     * </pre>
     *
     * <code>string method = 10;</code>
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;
    }

    /**
     * <pre>
     * Contains the path and query portion of the URL that was requested. For
     * example, if the URL was "http://example.com/app?name=val", the resource
     * would be "/app?name=val".  The fragment identifier, which is identified by
     * the `#` character, is not included.
     * </pre>
     *
     * <code>string resource = 11;</code>
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * <pre>
     * Contains the path and query portion of the URL that was requested. For
     * example, if the URL was "http://example.com/app?name=val", the resource
     * would be "/app?name=val".  The fragment identifier, which is identified by
     * the `#` character, is not included.
     * </pre>
     *
     * <code>string resource = 11;</code>
     */
    public function setResource($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource = $var;
    }

    /**
     * <pre>
     * HTTP version of request. Example: `"HTTP/1.1"`.
     * </pre>
     *
     * <code>string http_version = 12;</code>
     */
    public function getHttpVersion()
    {
        return $this->http_version;
    }

    /**
     * <pre>
     * HTTP version of request. Example: `"HTTP/1.1"`.
     * </pre>
     *
     * <code>string http_version = 12;</code>
     */
    public function setHttpVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->http_version = $var;
    }

    /**
     * <pre>
     * HTTP response status code. Example: 200, 404.
     * </pre>
     *
     * <code>int32 status = 13;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     * HTTP response status code. Example: 200, 404.
     * </pre>
     *
     * <code>int32 status = 13;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;
    }

    /**
     * <pre>
     * Size in bytes sent back to client by request.
     * </pre>
     *
     * <code>int64 response_size = 14;</code>
     */
    public function getResponseSize()
    {
        return $this->response_size;
    }

    /**
     * <pre>
     * Size in bytes sent back to client by request.
     * </pre>
     *
     * <code>int64 response_size = 14;</code>
     */
    public function setResponseSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->response_size = $var;
    }

    /**
     * <pre>
     * Referrer URL of request.
     * </pre>
     *
     * <code>string referrer = 15;</code>
     */
    public function getReferrer()
    {
        return $this->referrer;
    }

    /**
     * <pre>
     * Referrer URL of request.
     * </pre>
     *
     * <code>string referrer = 15;</code>
     */
    public function setReferrer($var)
    {
        GPBUtil::checkString($var, True);
        $this->referrer = $var;
    }

    /**
     * <pre>
     * User agent that made the request.
     * </pre>
     *
     * <code>string user_agent = 16;</code>
     */
    public function getUserAgent()
    {
        return $this->user_agent;
    }

    /**
     * <pre>
     * User agent that made the request.
     * </pre>
     *
     * <code>string user_agent = 16;</code>
     */
    public function setUserAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_agent = $var;
    }

    /**
     * <pre>
     * The logged-in user who made the request.
     * Most likely, this is the part of the user's email before the `&#64;` sign.  The
     * field value is the same for different requests from the same user, but
     * different users can have similar names.  This information is also
     * available to the application via the App Engine Users API.
     * This field will be populated starting with App Engine 1.9.21.
     * </pre>
     *
     * <code>string nickname = 40;</code>
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * <pre>
     * The logged-in user who made the request.
     * Most likely, this is the part of the user's email before the `&#64;` sign.  The
     * field value is the same for different requests from the same user, but
     * different users can have similar names.  This information is also
     * available to the application via the App Engine Users API.
     * This field will be populated starting with App Engine 1.9.21.
     * </pre>
     *
     * <code>string nickname = 40;</code>
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;
    }

    /**
     * <pre>
     * File or class that handled the request.
     * </pre>
     *
     * <code>string url_map_entry = 17;</code>
     */
    public function getUrlMapEntry()
    {
        return $this->url_map_entry;
    }

    /**
     * <pre>
     * File or class that handled the request.
     * </pre>
     *
     * <code>string url_map_entry = 17;</code>
     */
    public function setUrlMapEntry($var)
    {
        GPBUtil::checkString($var, True);
        $this->url_map_entry = $var;
    }

    /**
     * <pre>
     * Internet host and port number of the resource being requested.
     * </pre>
     *
     * <code>string host = 20;</code>
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * <pre>
     * Internet host and port number of the resource being requested.
     * </pre>
     *
     * <code>string host = 20;</code>
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;
    }

    /**
     * <pre>
     * An indication of the relative cost of serving this request.
     * </pre>
     *
     * <code>double cost = 21;</code>
     */
    public function getCost()
    {
        return $this->cost;
    }

    /**
     * <pre>
     * An indication of the relative cost of serving this request.
     * </pre>
     *
     * <code>double cost = 21;</code>
     */
    public function setCost($var)
    {
        GPBUtil::checkDouble($var);
        $this->cost = $var;
    }

    /**
     * <pre>
     * Queue name of the request, in the case of an offline request.
     * </pre>
     *
     * <code>string task_queue_name = 22;</code>
     */
    public function getTaskQueueName()
    {
        return $this->task_queue_name;
    }

    /**
     * <pre>
     * Queue name of the request, in the case of an offline request.
     * </pre>
     *
     * <code>string task_queue_name = 22;</code>
     */
    public function setTaskQueueName($var)
    {
        GPBUtil::checkString($var, True);
        $this->task_queue_name = $var;
    }

    /**
     * <pre>
     * Task name of the request, in the case of an offline request.
     * </pre>
     *
     * <code>string task_name = 23;</code>
     */
    public function getTaskName()
    {
        return $this->task_name;
    }

    /**
     * <pre>
     * Task name of the request, in the case of an offline request.
     * </pre>
     *
     * <code>string task_name = 23;</code>
     */
    public function setTaskName($var)
    {
        GPBUtil::checkString($var, True);
        $this->task_name = $var;
    }

    /**
     * <pre>
     * Whether this was a loading request for the instance.
     * </pre>
     *
     * <code>bool was_loading_request = 24;</code>
     */
    public function getWasLoadingRequest()
    {
        return $this->was_loading_request;
    }

    /**
     * <pre>
     * Whether this was a loading request for the instance.
     * </pre>
     *
     * <code>bool was_loading_request = 24;</code>
     */
    public function setWasLoadingRequest($var)
    {
        GPBUtil::checkBool($var);
        $this->was_loading_request = $var;
    }

    /**
     * <pre>
     * Time this request spent in the pending request queue.
     * </pre>
     *
     * <code>.google.protobuf.Duration pending_time = 25;</code>
     */
    public function getPendingTime()
    {
        return $this->pending_time;
    }

    /**
     * <pre>
     * Time this request spent in the pending request queue.
     * </pre>
     *
     * <code>.google.protobuf.Duration pending_time = 25;</code>
     */
    public function setPendingTime(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->pending_time = $var;
    }

    /**
     * <pre>
     * If the instance processing this request belongs to a manually scaled
     * module, then this is the 0-based index of the instance. Otherwise, this
     * value is -1.
     * </pre>
     *
     * <code>int32 instance_index = 26;</code>
     */
    public function getInstanceIndex()
    {
        return $this->instance_index;
    }

    /**
     * <pre>
     * If the instance processing this request belongs to a manually scaled
     * module, then this is the 0-based index of the instance. Otherwise, this
     * value is -1.
     * </pre>
     *
     * <code>int32 instance_index = 26;</code>
     */
    public function setInstanceIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->instance_index = $var;
    }

    /**
     * <pre>
     * Whether this request is finished or active.
     * </pre>
     *
     * <code>bool finished = 27;</code>
     */
    public function getFinished()
    {
        return $this->finished;
    }

    /**
     * <pre>
     * Whether this request is finished or active.
     * </pre>
     *
     * <code>bool finished = 27;</code>
     */
    public function setFinished($var)
    {
        GPBUtil::checkBool($var);
        $this->finished = $var;
    }

    /**
     * <pre>
     * Whether this is the first `RequestLog` entry for this request.  If an
     * active request has several `RequestLog` entries written to Stackdriver
     * Logging, then this field will be set for one of them.
     * </pre>
     *
     * <code>bool first = 42;</code>
     */
    public function getFirst()
    {
        return $this->first;
    }

    /**
     * <pre>
     * Whether this is the first `RequestLog` entry for this request.  If an
     * active request has several `RequestLog` entries written to Stackdriver
     * Logging, then this field will be set for one of them.
     * </pre>
     *
     * <code>bool first = 42;</code>
     */
    public function setFirst($var)
    {
        GPBUtil::checkBool($var);
        $this->first = $var;
    }

    /**
     * <pre>
     * An identifier for the instance that handled the request.
     * </pre>
     *
     * <code>string instance_id = 28;</code>
     */
    public function getInstanceId()
    {
        return $this->instance_id;
    }

    /**
     * <pre>
     * An identifier for the instance that handled the request.
     * </pre>
     *
     * <code>string instance_id = 28;</code>
     */
    public function setInstanceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->instance_id = $var;
    }

    /**
     * <pre>
     * A list of log lines emitted by the application while serving this request.
     * </pre>
     *
     * <code>repeated .google.appengine.logging.v1.LogLine line = 29;</code>
     */
    public function getLine()
    {
        return $this->line;
    }

    /**
     * <pre>
     * A list of log lines emitted by the application while serving this request.
     * </pre>
     *
     * <code>repeated .google.appengine.logging.v1.LogLine line = 29;</code>
     */
    public function setLine(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Appengine\Logging\V1\LogLine::class);
        $this->line = $var;
    }

    /**
     * <pre>
     * App Engine release version.
     * </pre>
     *
     * <code>string app_engine_release = 38;</code>
     */
    public function getAppEngineRelease()
    {
        return $this->app_engine_release;
    }

    /**
     * <pre>
     * App Engine release version.
     * </pre>
     *
     * <code>string app_engine_release = 38;</code>
     */
    public function setAppEngineRelease($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_engine_release = $var;
    }

    /**
     * <pre>
     * Stackdriver Trace identifier for this request.
     * </pre>
     *
     * <code>string trace_id = 39;</code>
     */
    public function getTraceId()
    {
        return $this->trace_id;
    }

    /**
     * <pre>
     * Stackdriver Trace identifier for this request.
     * </pre>
     *
     * <code>string trace_id = 39;</code>
     */
    public function setTraceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->trace_id = $var;
    }

    /**
     * <pre>
     * Source code for the application that handled this request. There can be
     * more than one source reference per deployed application if source code is
     * distributed among multiple repositories.
     * </pre>
     *
     * <code>repeated .google.appengine.logging.v1.SourceReference source_reference = 41;</code>
     */
    public function getSourceReference()
    {
        return $this->source_reference;
    }

    /**
     * <pre>
     * Source code for the application that handled this request. There can be
     * more than one source reference per deployed application if source code is
     * distributed among multiple repositories.
     * </pre>
     *
     * <code>repeated .google.appengine.logging.v1.SourceReference source_reference = 41;</code>
     */
    public function setSourceReference(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Appengine\Logging\V1\SourceReference::class);
        $this->source_reference = $var;
    }

}

