<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: google/logging/type/log_severity.proto
//   Date: 2017-06-13 04:26:02

namespace google\logging\type {

  class LogSeverity extends \DrSlump\Protobuf\Enum {
    const DEFAULT = 0;
    const DEBUG = 100;
    const INFO = 200;
    const NOTICE = 300;
    const WARNING = 400;
    const ERROR = 500;
    const CRITICAL = 600;
    const ALERT = 700;
    const EMERGENCY = 800;
  }
}
