<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: google/genomics/v1/readgroup.proto
//   Date: 2017-06-13 04:25:43

namespace google\genomics\v1\ReadGroup {

  class Experiment extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $library_id = null;
    
    /**  @var string */
    public $platform_unit = null;
    
    /**  @var string */
    public $sequencing_center = null;
    
    /**  @var string */
    public $instrument_model = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.genomics.v1.ReadGroup.Experiment');

      // OPTIONAL STRING library_id = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "library_id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING platform_unit = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "platform_unit";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING sequencing_center = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "sequencing_center";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING instrument_model = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "instrument_model";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <library_id> has a value
     *
     * @return boolean
     */
    public function hasLibraryId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <library_id> value
     *
     * @return \google\genomics\v1\ReadGroup\Experiment
     */
    public function clearLibraryId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <library_id> value
     *
     * @return string
     */
    public function getLibraryId(){
      return $this->_get(1);
    }
    
    /**
     * Set <library_id> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup\Experiment
     */
    public function setLibraryId( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <platform_unit> has a value
     *
     * @return boolean
     */
    public function hasPlatformUnit(){
      return $this->_has(2);
    }
    
    /**
     * Clear <platform_unit> value
     *
     * @return \google\genomics\v1\ReadGroup\Experiment
     */
    public function clearPlatformUnit(){
      return $this->_clear(2);
    }
    
    /**
     * Get <platform_unit> value
     *
     * @return string
     */
    public function getPlatformUnit(){
      return $this->_get(2);
    }
    
    /**
     * Set <platform_unit> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup\Experiment
     */
    public function setPlatformUnit( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <sequencing_center> has a value
     *
     * @return boolean
     */
    public function hasSequencingCenter(){
      return $this->_has(3);
    }
    
    /**
     * Clear <sequencing_center> value
     *
     * @return \google\genomics\v1\ReadGroup\Experiment
     */
    public function clearSequencingCenter(){
      return $this->_clear(3);
    }
    
    /**
     * Get <sequencing_center> value
     *
     * @return string
     */
    public function getSequencingCenter(){
      return $this->_get(3);
    }
    
    /**
     * Set <sequencing_center> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup\Experiment
     */
    public function setSequencingCenter( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <instrument_model> has a value
     *
     * @return boolean
     */
    public function hasInstrumentModel(){
      return $this->_has(4);
    }
    
    /**
     * Clear <instrument_model> value
     *
     * @return \google\genomics\v1\ReadGroup\Experiment
     */
    public function clearInstrumentModel(){
      return $this->_clear(4);
    }
    
    /**
     * Get <instrument_model> value
     *
     * @return string
     */
    public function getInstrumentModel(){
      return $this->_get(4);
    }
    
    /**
     * Set <instrument_model> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup\Experiment
     */
    public function setInstrumentModel( $value){
      return $this->_set(4, $value);
    }
  }
}

namespace google\genomics\v1\ReadGroup {

  class Program extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $command_line = null;
    
    /**  @var string */
    public $id = null;
    
    /**  @var string */
    public $name = null;
    
    /**  @var string */
    public $prev_program_id = null;
    
    /**  @var string */
    public $version = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.genomics.v1.ReadGroup.Program');

      // OPTIONAL STRING command_line = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "command_line";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING id = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING name = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING prev_program_id = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "prev_program_id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING version = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "version";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <command_line> has a value
     *
     * @return boolean
     */
    public function hasCommandLine(){
      return $this->_has(1);
    }
    
    /**
     * Clear <command_line> value
     *
     * @return \google\genomics\v1\ReadGroup\Program
     */
    public function clearCommandLine(){
      return $this->_clear(1);
    }
    
    /**
     * Get <command_line> value
     *
     * @return string
     */
    public function getCommandLine(){
      return $this->_get(1);
    }
    
    /**
     * Set <command_line> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup\Program
     */
    public function setCommandLine( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <id> has a value
     *
     * @return boolean
     */
    public function hasId(){
      return $this->_has(2);
    }
    
    /**
     * Clear <id> value
     *
     * @return \google\genomics\v1\ReadGroup\Program
     */
    public function clearId(){
      return $this->_clear(2);
    }
    
    /**
     * Get <id> value
     *
     * @return string
     */
    public function getId(){
      return $this->_get(2);
    }
    
    /**
     * Set <id> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup\Program
     */
    public function setId( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <name> has a value
     *
     * @return boolean
     */
    public function hasName(){
      return $this->_has(3);
    }
    
    /**
     * Clear <name> value
     *
     * @return \google\genomics\v1\ReadGroup\Program
     */
    public function clearName(){
      return $this->_clear(3);
    }
    
    /**
     * Get <name> value
     *
     * @return string
     */
    public function getName(){
      return $this->_get(3);
    }
    
    /**
     * Set <name> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup\Program
     */
    public function setName( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <prev_program_id> has a value
     *
     * @return boolean
     */
    public function hasPrevProgramId(){
      return $this->_has(4);
    }
    
    /**
     * Clear <prev_program_id> value
     *
     * @return \google\genomics\v1\ReadGroup\Program
     */
    public function clearPrevProgramId(){
      return $this->_clear(4);
    }
    
    /**
     * Get <prev_program_id> value
     *
     * @return string
     */
    public function getPrevProgramId(){
      return $this->_get(4);
    }
    
    /**
     * Set <prev_program_id> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup\Program
     */
    public function setPrevProgramId( $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <version> has a value
     *
     * @return boolean
     */
    public function hasVersion(){
      return $this->_has(5);
    }
    
    /**
     * Clear <version> value
     *
     * @return \google\genomics\v1\ReadGroup\Program
     */
    public function clearVersion(){
      return $this->_clear(5);
    }
    
    /**
     * Get <version> value
     *
     * @return string
     */
    public function getVersion(){
      return $this->_get(5);
    }
    
    /**
     * Set <version> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup\Program
     */
    public function setVersion( $value){
      return $this->_set(5, $value);
    }
  }
}

namespace google\genomics\v1\ReadGroup {

  class InfoEntry extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $key = null;
    
    /**  @var \google\protobuf\ListValue */
    public $value = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.genomics.v1.ReadGroup.InfoEntry');

      // OPTIONAL STRING key = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "key";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE value = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "value";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\protobuf\ListValue';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <key> has a value
     *
     * @return boolean
     */
    public function hasKey(){
      return $this->_has(1);
    }
    
    /**
     * Clear <key> value
     *
     * @return \google\genomics\v1\ReadGroup\InfoEntry
     */
    public function clearKey(){
      return $this->_clear(1);
    }
    
    /**
     * Get <key> value
     *
     * @return string
     */
    public function getKey(){
      return $this->_get(1);
    }
    
    /**
     * Set <key> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup\InfoEntry
     */
    public function setKey( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <value> has a value
     *
     * @return boolean
     */
    public function hasValue(){
      return $this->_has(2);
    }
    
    /**
     * Clear <value> value
     *
     * @return \google\genomics\v1\ReadGroup\InfoEntry
     */
    public function clearValue(){
      return $this->_clear(2);
    }
    
    /**
     * Get <value> value
     *
     * @return \google\protobuf\ListValue
     */
    public function getValue(){
      return $this->_get(2);
    }
    
    /**
     * Set <value> value
     *
     * @param \google\protobuf\ListValue $value
     * @return \google\genomics\v1\ReadGroup\InfoEntry
     */
    public function setValue(\google\protobuf\ListValue $value){
      return $this->_set(2, $value);
    }
  }
}

namespace google\genomics\v1 {

  class ReadGroup extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $id = null;
    
    /**  @var string */
    public $dataset_id = null;
    
    /**  @var string */
    public $name = null;
    
    /**  @var string */
    public $description = null;
    
    /**  @var string */
    public $sample_id = null;
    
    /**  @var \google\genomics\v1\ReadGroup\Experiment */
    public $experiment = null;
    
    /**  @var int */
    public $predicted_insert_size = null;
    
    /**  @var \google\genomics\v1\ReadGroup\Program[]  */
    public $programs = array();
    
    /**  @var string */
    public $reference_set_id = null;
    
    /**  @var \google\genomics\v1\ReadGroup\InfoEntry[]  */
    public $info = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.genomics.v1.ReadGroup');

      // OPTIONAL STRING id = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING dataset_id = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "dataset_id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING name = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING description = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "description";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING sample_id = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "sample_id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE experiment = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "experiment";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\google\genomics\v1\ReadGroup\Experiment';
      $descriptor->addField($f);

      // OPTIONAL INT32 predicted_insert_size = 7
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 7;
      $f->name      = "predicted_insert_size";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED MESSAGE programs = 10
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 10;
      $f->name      = "programs";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\google\genomics\v1\ReadGroup\Program';
      $descriptor->addField($f);

      // OPTIONAL STRING reference_set_id = 11
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 11;
      $f->name      = "reference_set_id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED MESSAGE info = 12
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 12;
      $f->name      = "info";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\google\genomics\v1\ReadGroup\InfoEntry';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <id> has a value
     *
     * @return boolean
     */
    public function hasId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <id> value
     *
     * @return \google\genomics\v1\ReadGroup
     */
    public function clearId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <id> value
     *
     * @return string
     */
    public function getId(){
      return $this->_get(1);
    }
    
    /**
     * Set <id> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup
     */
    public function setId( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <dataset_id> has a value
     *
     * @return boolean
     */
    public function hasDatasetId(){
      return $this->_has(2);
    }
    
    /**
     * Clear <dataset_id> value
     *
     * @return \google\genomics\v1\ReadGroup
     */
    public function clearDatasetId(){
      return $this->_clear(2);
    }
    
    /**
     * Get <dataset_id> value
     *
     * @return string
     */
    public function getDatasetId(){
      return $this->_get(2);
    }
    
    /**
     * Set <dataset_id> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup
     */
    public function setDatasetId( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <name> has a value
     *
     * @return boolean
     */
    public function hasName(){
      return $this->_has(3);
    }
    
    /**
     * Clear <name> value
     *
     * @return \google\genomics\v1\ReadGroup
     */
    public function clearName(){
      return $this->_clear(3);
    }
    
    /**
     * Get <name> value
     *
     * @return string
     */
    public function getName(){
      return $this->_get(3);
    }
    
    /**
     * Set <name> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup
     */
    public function setName( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <description> has a value
     *
     * @return boolean
     */
    public function hasDescription(){
      return $this->_has(4);
    }
    
    /**
     * Clear <description> value
     *
     * @return \google\genomics\v1\ReadGroup
     */
    public function clearDescription(){
      return $this->_clear(4);
    }
    
    /**
     * Get <description> value
     *
     * @return string
     */
    public function getDescription(){
      return $this->_get(4);
    }
    
    /**
     * Set <description> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup
     */
    public function setDescription( $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <sample_id> has a value
     *
     * @return boolean
     */
    public function hasSampleId(){
      return $this->_has(5);
    }
    
    /**
     * Clear <sample_id> value
     *
     * @return \google\genomics\v1\ReadGroup
     */
    public function clearSampleId(){
      return $this->_clear(5);
    }
    
    /**
     * Get <sample_id> value
     *
     * @return string
     */
    public function getSampleId(){
      return $this->_get(5);
    }
    
    /**
     * Set <sample_id> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup
     */
    public function setSampleId( $value){
      return $this->_set(5, $value);
    }
    
    /**
     * Check if <experiment> has a value
     *
     * @return boolean
     */
    public function hasExperiment(){
      return $this->_has(6);
    }
    
    /**
     * Clear <experiment> value
     *
     * @return \google\genomics\v1\ReadGroup
     */
    public function clearExperiment(){
      return $this->_clear(6);
    }
    
    /**
     * Get <experiment> value
     *
     * @return \google\genomics\v1\ReadGroup\Experiment
     */
    public function getExperiment(){
      return $this->_get(6);
    }
    
    /**
     * Set <experiment> value
     *
     * @param \google\genomics\v1\ReadGroup\Experiment $value
     * @return \google\genomics\v1\ReadGroup
     */
    public function setExperiment(\google\genomics\v1\ReadGroup\Experiment $value){
      return $this->_set(6, $value);
    }
    
    /**
     * Check if <predicted_insert_size> has a value
     *
     * @return boolean
     */
    public function hasPredictedInsertSize(){
      return $this->_has(7);
    }
    
    /**
     * Clear <predicted_insert_size> value
     *
     * @return \google\genomics\v1\ReadGroup
     */
    public function clearPredictedInsertSize(){
      return $this->_clear(7);
    }
    
    /**
     * Get <predicted_insert_size> value
     *
     * @return int
     */
    public function getPredictedInsertSize(){
      return $this->_get(7);
    }
    
    /**
     * Set <predicted_insert_size> value
     *
     * @param int $value
     * @return \google\genomics\v1\ReadGroup
     */
    public function setPredictedInsertSize( $value){
      return $this->_set(7, $value);
    }
    
    /**
     * Check if <programs> has a value
     *
     * @return boolean
     */
    public function hasPrograms(){
      return $this->_has(10);
    }
    
    /**
     * Clear <programs> value
     *
     * @return \google\genomics\v1\ReadGroup
     */
    public function clearPrograms(){
      return $this->_clear(10);
    }
    
    /**
     * Get <programs> value
     *
     * @param int $idx
     * @return \google\genomics\v1\ReadGroup\Program
     */
    public function getPrograms($idx = NULL){
      return $this->_get(10, $idx);
    }
    
    /**
     * Set <programs> value
     *
     * @param \google\genomics\v1\ReadGroup\Program $value
     * @return \google\genomics\v1\ReadGroup
     */
    public function setPrograms(\google\genomics\v1\ReadGroup\Program $value, $idx = NULL){
      return $this->_set(10, $value, $idx);
    }
    
    /**
     * Get all elements of <programs>
     *
     * @return \google\genomics\v1\ReadGroup\Program[]
     */
    public function getProgramsList(){
     return $this->_get(10);
    }
    
    /**
     * Add a new element to <programs>
     *
     * @param \google\genomics\v1\ReadGroup\Program $value
     * @return \google\genomics\v1\ReadGroup
     */
    public function addPrograms(\google\genomics\v1\ReadGroup\Program $value){
     return $this->_add(10, $value);
    }
    
    /**
     * Check if <reference_set_id> has a value
     *
     * @return boolean
     */
    public function hasReferenceSetId(){
      return $this->_has(11);
    }
    
    /**
     * Clear <reference_set_id> value
     *
     * @return \google\genomics\v1\ReadGroup
     */
    public function clearReferenceSetId(){
      return $this->_clear(11);
    }
    
    /**
     * Get <reference_set_id> value
     *
     * @return string
     */
    public function getReferenceSetId(){
      return $this->_get(11);
    }
    
    /**
     * Set <reference_set_id> value
     *
     * @param string $value
     * @return \google\genomics\v1\ReadGroup
     */
    public function setReferenceSetId( $value){
      return $this->_set(11, $value);
    }
    
    /**
     * Check if <info> has a value
     *
     * @return boolean
     */
    public function hasInfo(){
      return $this->_has(12);
    }
    
    /**
     * Clear <info> value
     *
     * @return \google\genomics\v1\ReadGroup
     */
    public function clearInfo(){
      return $this->_clear(12);
    }
    
    /**
     * Get <info> value
     *
     * @param int $idx
     * @return \google\genomics\v1\ReadGroup\InfoEntry
     */
    public function getInfo($idx = NULL){
      return $this->_get(12, $idx);
    }
    
    /**
     * Set <info> value
     *
     * @param \google\genomics\v1\ReadGroup\InfoEntry $value
     * @return \google\genomics\v1\ReadGroup
     */
    public function setInfo(\google\genomics\v1\ReadGroup\InfoEntry $value, $idx = NULL){
      return $this->_set(12, $value, $idx);
    }
    
    /**
     * Get all elements of <info>
     *
     * @return \google\genomics\v1\ReadGroup\InfoEntry[]
     */
    public function getInfoList(){
     return $this->_get(12);
    }
    
    /**
     * Add a new element to <info>
     *
     * @param \google\genomics\v1\ReadGroup\InfoEntry $value
     * @return \google\genomics\v1\ReadGroup
     */
    public function addInfo(\google\genomics\v1\ReadGroup\InfoEntry $value){
     return $this->_add(12, $value);
    }
  }
}

